### ISSUE TITLE
Bazel build fails on macOS (lotus/terminal related issues)

### ISSUE THREAD

**Issue by lukaszgryglicki** [kubernetes/test-infra#2571] opened 2017-04-25 07:42 UTC
Current `master` branch:
```
iMac-Adm:prow lukasz$ bazel build //prow/cmd/hook/...
WARNING: /private/var/tmp/_bazel_lukasz/91522e51e78fc14827690a9c012f5556/external/nodejs_darwin_amd64/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_lukasz/91522e51e78fc14827690a9c012f5556/external/nodejs_darwin_amd64/WORKSPACE (@org_pubref_rules_node_toolchain) does not match the name given in the repository's definition (@nodejs_darwin_amd64); this will cause a build error in future versions.
INFO: Found 5 targets...
ERROR: /Users/lukasz/dev/go/src/k8s.io/test-infra/vendor/BUILD:65:1: error executing shell command: 'bazel-out/local-fastbuild/bin/vendor/bazel-out/local-fastbuild/bin/vendor/github.com/Sirupsen/logrus.a.GoCompileFile.params' failed: Process exited with status 1 [sandboxed].
k8s.io/test-infra/vendor/github.com/Sirupsen/logrus/terminal_notwindows.go:18: undefined: Termios
k8s.io/test-infra/vendor/github.com/Sirupsen/logrus/terminal_notwindows.go:19: undefined: ioctlReadTermios
Use --strategy=GoCompile=standalone to disable sandboxing for the failing actions.
INFO: Elapsed time: 1.221s, Critical Path: 0.90s
iMac-Adm:prow lukasz$ 
```

And if I replace `terminal_notwindows.go` with `terminal_bsd.go` (that helped few days ago):

```
iMac-Adm:prow lukasz$ bazel build //prow/cmd/hook/...
WARNING: /private/var/tmp/_bazel_lukasz/91522e51e78fc14827690a9c012f5556/external/nodejs_darwin_amd64/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_lukasz/91522e51e78fc14827690a9c012f5556/external/nodejs_darwin_amd64/WORKSPACE (@org_pubref_rules_node_toolchain) does not match the name given in the repository's definition (@nodejs_darwin_amd64); this will cause a build error in future versions.
INFO: Found 5 targets...
ERROR: /Users/lukasz/dev/go/src/k8s.io/test-infra/vendor/BUILD:65:1: error executing shell command: 'bazel-out/local-fastbuild/bin/vendor/bazel-out/local-fastbuild/bin/vendor/github.com/Sirupsen/logrus.a.GoCompileFile.params' failed: Process exited with status 1 [sandboxed].
k8s.io/test-infra/vendor/github.com/Sirupsen/logrus/text_formatter.go:28: undefined: IsTerminal
Use --strategy=GoCompile=standalone to disable sandboxing for the failing actions.
INFO: Elapsed time: 0.784s, Critical Path: 0.46s
```

Adding this lines:
```
+type Termios syscall.Termios
+const ioctlReadTermios = syscall.TIOCGETA
```

to `vendor/github.com/Sirupsen/logrus/terminal_notwindows.go` (just before `func IsTerminal`) helps locally for me (on my macOS Sierra), but because the name suggest "not windows" then I suppose it should be tested in many OS-es.

And if I compile/run manually (with Makefile or just `go build`/`go run`) all works just fine.... seems like this is bazel related?

**Comment by spxtr** [comment] 2017-04-25 17:33
Possible dupe of #2315?

You can just use `go build` for developing prow. I have the default `make` rule set to do a `go build` and `go test`.

**Comment by lukaszgryglicki** [comment] 2017-04-25 18:27
Well I can work locally - this is not a problem at all.
I'm only signalling that there is such an issue.

**Closed** 2017-06-27 19:03 UTC
