### ISSUE TITLE
Remove "lgtm" after PR changes?

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#6070] opened 2017-12-22 06:29 UTC
In test-infra, after an approved and lgtm'd PR rebasing or changing, the `lgtm` is not removed. Then the PR will be merged. (example: #5904). Seems like it's not safe, right? Suppose that I add some ruinous code by mistake or intentionally (:smile:), something would be broken after the merge.

/cc @cjwagner @krzyzacy @BenTheElder -

**Comment by spxtr** [comment] 2017-12-22 09:03
If it's *broken* broken then the presubmit should catch it :)

Dupe of #3795 I think.

**Closed by spxtr** 2017-12-22 09:03 UTC

**Comment by xiangpengzhao** [comment] 2017-12-22 09:27
Oh cool! Didn't notice that :)
