### ISSUE TITLE
Prow Build log is completely empty and the test is not getting terminated 

### ISSUE THREAD

**Issue by Ark-kun** [kubernetes/test-infra#12636] opened 2019-05-14 22:04 UTC
Prow Build log is completely empty and the test duration shown is above termination thresholds.

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/1331/kubeflow-pipeline-sample-test/1128399059598446599

```
Test started today at 1:39 PM is still running after 2h15m38s. (less info)

Status	Pending
Started	2019-05-14 20:39:45 +0000 UTC
Elapsed	2h15m38s
```

**Comment by stevekuznetsov** [comment] 2019-05-14 22:54
So I think this is working as implemented. I would like to see what the timeout value is set to for this test, and if possible the Pod YAML and ProwJob YAML associated with it.

**Comment by stevekuznetsov** [comment] 2019-05-14 22:56
See also https://github.com/kubernetes/test-infra/issues/11631

**Comment by stevekuznetsov** [comment] 2019-05-14 22:57
Timeout is set to 2h:

https://github.com/kubernetes/test-infra/blob/21f2d9dca8dd8bbeb7fc1f4df997294aa9d839a2/prow/config.yaml#L7

So this job should be terminated soon.

**Comment by stevekuznetsov** [comment] 2019-05-14 22:58
This is a dupe of the above linked issue, so I will close this and do more debugging there.

/close

**Comment by krzyzacy** [comment] 2019-05-14 22:59
(I don't think this is a decorated job :-) )

**Comment by krzyzacy** [comment] 2019-05-14 23:09
@Ark-kun so kubeflow already send us org-level webhooks, looks like kubeflow/pipelines is also sending repo-level webhooks? Please delete the repo-level webhook :-)

**Comment by stevekuznetsov** [comment] 2019-05-14 23:15
This was a decorated job, so 

/close 
:grimacing:

**Comment by cjwagner** [comment] 2019-05-15 05:02
> @Ark-kun so kubeflow already send us org-level webhooks, looks like kubeflow/pipelines is also sending repo-level webhooks? Please delete the repo-level webhook :-)

https://github.com/kubeflow/pipelines/issues/1304

**Comment by Ark-kun** [comment] 2019-05-21 22:53
> So this job should be terminated soon.

```still running after 170h13m1s```

**Comment by Ark-kun** [comment] 2019-06-05 22:09
> Please delete the repo-level webhook

We've fixed that couple of weeks ago. Thanks

I have another case: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/1445/kubeflow-pipeline-e2e-test/1136105751991816192

This one has build log, but it's still running after 19 hours.

/reopen

**Comment by stevekuznetsov** [comment] 2019-06-05 22:21
@Ark-kun so I still would like this closed since we see the other issue is still open to track it ... and please contact the on-call in testing ops slack channel to get the Pod YAML for this, so we can debug, otherwise no further progress can be made. I've contacted on-call myself this time.

/close

**Comment by Ark-kun** [comment] 2019-06-20 08:14
Adding another instance... https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/1483/kubeflow-pipeline-sample-test/1140974150098096128

**Comment by Ark-kun** [comment] 2019-10-11 18:47
Another instance: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/2292/kubeflow-pipeline-sample-test/1182504023488466945

**Comment by Ark-kun** [comment] 2019-10-14 18:30
`Test started 08/10/2019 is still running after 1559h51m55s.`

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/3632/kubeflow-presubmit/1160258321232433152/

**Comment by Ark-kun** [comment] 2019-10-16 23:56
> we see the other issue is still open to track it

Can you please point me to that issue?

**Comment by Ark-kun** [comment] 2019-11-27 04:00
Another instance: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/2645/kubeflow-pipeline-sample-test/1199518175478157314

/reopen

**Comment by stevekuznetsov** [comment] 2019-11-27 22:18
This is _still_ a duplicate of https://github.com/kubernetes/test-infra/issues/11631

We _still_ need the report to have the data I expected before and it _still_ needs to be routed to the on-call on Slack. Please follow those instructions next time you see this so that something can actually be done.

/close

**Closed by stevekuznetsov** 2019-11-27 22:18 UTC
Labels: kind/bug

**Comment by Ark-kun** [comment] 2019-11-27 22:26
> This is _still_ a duplicate of #11631

I see. In October I asked to point me to the issue (as #11631 seemed unrelated) and got no answer: https://github.com/kubernetes/test-infra/issues/12636#issuecomment-542938316

>We still need the report to have the data I expected before and it still needs to be routed to the on-call on Slack. Please follow those instructions next time you see this so that something can actually be done.

Thank you. I'll try following that procedure (after I find it...)
