### ISSUE TITLE
Test running for a long time with empty log

### ISSUE THREAD

**Issue by Ark-kun** [kubernetes/test-infra#15417] opened 2019-11-27 04:00 UTC
Same as https://github.com/kubernetes/test-infra/issues/12636
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/2645/kubeflow-pipeline-sample-test/1199518175478157314

**Comment by stevekuznetsov** [comment] 2019-11-27 22:18
Dupe of https://github.com/kubernetes/test-infra/issues/11631
/close

**Closed by stevekuznetsov** 2019-11-27 22:18 UTC
Labels: kind/bug
