### ISSUE TITLE
`go get k8s.io/test-infra/kubetest` seems to fail

### ISSUE THREAD

**Issue by seeker89** [kubernetes/test-infra#14825] opened 2019-10-17 08:04 UTC
**What happened**:

When running `go get -u k8s.io/test-infra/kubetest` from [the README](https://github.com/kubernetes/test-infra/tree/master/kubetest#installation) I run into errors:

```sh
# github.com/aws/aws-k8s-tester/vendor/k8s.io/client-go/rest
../../aws/aws-k8s-tester/vendor/k8s.io/client-go/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
        have (*versioned.Decoder)
        want (watch.Decoder, watch.Reporter)
# k8s.io/client-go/transport
../../../k8s.io/client-go/transport/round_trippers.go:70:11: cannot convert klog.V(9) (type klog.Verbose) to type bool
../../../k8s.io/client-go/transport/round_trippers.go:72:11: cannot convert klog.V(8) (type klog.Verbose) to type bool
../../../k8s.io/client-go/transport/round_trippers.go:74:11: cannot convert klog.V(7) (type klog.Verbose) to type bool
../../../k8s.io/client-go/transport/round_trippers.go:76:11: cannot convert klog.V(6) (type klog.Verbose) to type bool
```

**What you expected to happen**:

I expected it to compile correctly.

**How to reproduce it (as minimally and precisely as possible)**:

Run `go get -u k8s.io/test-infra/kubetest` on go version 1.13.1 on linux.

**Anything else we need to know?**:

```sh
$ go version
go version go1.13.1 linux/amd64
$ uname -a
Linux <host> 4.15.0-55-generic #60-Ubuntu <> x86_64 x86_64 x86_64 GNU/Linux
```

Looks similar to https://github.com/kubernetes/client-go/issues/654

**Comment by dims** [comment] 2019-10-17 13:04
duplicate of https://github.com/kubernetes/test-infra/issues/14712

please see tips there

/close

**Closed by dims** 2019-10-17 13:04 UTC
Labels: kind/bug
