### ISSUE TITLE
SSH metadata causing issues in GKE PR tests.

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#725] opened 2016-09-30 21:16 UTC
GKE needs to add SSH keys to your project. We have 70 PR agents adding their metadata, and after they all do it then PRs start failing. The fix is to go in and delete all SSH keys other than `jenkins@pull-jenkins-master` and the running GKE keys. This is super gross, but there's not really a good way to do it.

The underlying issue is that the metadata is just a big text blob and we can't really update it without racing, unless we ensure that no PR tests are running at the moment.

**Comment by gmarek** [comment] 2016-10-06 06:55
It's a dupe of a P0 flake, so I'm bumping priority.

**Comment by spxtr** [comment] 2016-10-06 17:56
I'll try to have a fix out ASAP. It was p0 because when it fails it fails over and over again until the project is cleaned up.

**Closed** 2016-10-06 23:32 UTC
Labels: jenkins, priority/P0

**Comment by spxtr** [comment] 2016-10-06 23:43
Looks like it worked :)
