### ISSUE TITLE
Mungebot: Approval notif refreshes constantly if commit date is in the future

### ISSUE THREAD

**Issue by apelisse** [kubernetes/test-infra#1965] opened 2017-02-22 15:32 UTC
In https://github.com/kubernetes/kubernetes/pull/41775, the approval notification kept being removed and added. According to logs, it is removed because the code is more recent than the notification it just posted. It's probably because the clock of the committer is improperly set.

Let's find a way to prevent that from happening again.

**Comment by apelisse** [comment] 2017-02-22 15:33
cc @grodrigues3

**Comment by grodrigues3** [comment] 2017-02-22 16:08
Since we decided approval should be independent of commit time (i.e. if you ever approve, your approval sticks until canceled), I think this problem should be fixed in the refactored implementation

**Comment by apelisse** [comment] 2017-02-22 17:11
It's close to sticky approval, but it's unrelated.

> (i.e. if you ever approve, your approval sticks until canceled)

That's not exactly true. if you approve all the files, let's say `a` and `b`, and then new code is pushed for  `c` for which you're not an approver, the approval will be removed. And at this time, we probably need to show the approval notification to explain why that is.

**Comment by CaoShuFeng** [comment] 2017-04-10 08:41
I have another problem. I think.
1. make a pull request with the commit time in the feature.
2. someone add a LGTM label.
3. robot remove the LGTM lable because the commit time is later than the LGTM lable.

**Comment by grodrigues3** [comment] 2017-04-10 17:17
@CaoShuFeng this is expected behavior I believe.  The approved label should stay on, but if you commit to a PR after the LGTM label is added, the code has changed and needs to be re-reviewed.

**Comment by grodrigues3** [comment] 2017-06-30 17:28
/area mungegithub 

missed an h

**Comment by fejta** [comment] 2017-09-30 00:12
Moving to a prow plugin

**Closed by fejta** 2017-09-30 00:12 UTC
Labels: area/mungegithub
