### ISSUE TITLE
gke tests are missing log artifacts

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/test-infra#4323] opened 2017-09-01 18:47 UTC
Some upgrade tests are missings logs, making them practically impossible to debug and fix. e.g. https://github.com/kubernetes/kubernetes/issues/50793#issuecomment-326300909

Apparently we're using the wrong scp command.

/assign @shyamjvs

slack conversation:

```
2:36 PM] 
fejta
yes because a) upgrading will reboot the master and b) we collect logs at the end of the run


[2:37 PM] 
@shyamjvs have you given any thoughts to this? Does your log collector help here?


[2:40 PM] 
One idea would be make the test which does the upgrade first dump logs if requested. Using a pattern similar to https://github.com/kubernetes/kubernetes/blob/0596891e424b4d9e1858117641cf93c7cf266450/test/e2e/e2e.go#L193
GitHub
kubernetes/kubernetes
kubernetes - Production-Grade Container Scheduling and Management
 


[2:41 PM] 
Alternatively add a dump cluster logs piece:
https://github.com/kubernetes/test-infra/blob/master/kubetest/e2e.go#L217

Before running upgrades: 
https://github.com/kubernetes/test-infra/blob/master/kubetest/e2e.go#L164
GitHub
kubernetes/test-infra
test-infra - Test infrastructure for the Kubernetes project.
 


[3:05 PM] 
abgworrall joined #sig-testing.



----- Today September 1st, 2017 -----
[5:50 AM] 
shyamjvs @fejta @ericchiang Upgrading the master leading to reboot is not the reason why the logs are failing to be collected


[5:52 AM] 
The log-dump script has nothing much to do with master reboot... it's collecting logs from nodes by individually SCP'ing to them


[5:54 AM] 
(which can happen even if the master is down (except for logs of the master itself))


[6:09 AM] 
shyamjvs The issue is in this line - https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump/log-dump.sh#L109
GitHub
kubernetes/kubernetes
kubernetes - Production-Grade Container Scheduling and Management
 


[6:11 AM] 
We're setting 'use_custom_instances_list' function for gke, which makes the script use scp. And scp expects an IP address (while we're actually providing the VM name there) (edited)


[6:13 AM] 
I'll send a PR to use 'gcloud compute scp' instead of 'scp' when node name is provided instead of IP. That should fix it.
```

**Comment by shyamjvs** [comment] 2017-09-01 22:38
Sorry I got busy with a few critical SQ issues. Sent out the fix - https://github.com/kubernetes/kubernetes/pull/51834

**Comment by ericchiang** [comment] 2017-09-05 16:51
@shyamjvs I'm still seeing missing artifacts. Specifically on this upgrade test https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-cluster-new

For example the most recent build doesn't have the normal artifacts we'd expect https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-new/194

Has this fix not been rolled out yet?

**Comment by shyamjvs** [comment] 2017-09-05 17:03
Yes, the fix was in pr #4347 (which got merged a while ago). It is yet to roll out.

@krzyzazy Could you build the new kubetest and related images and send our the relevant pr? I'm facing the weird bazel issue that we discussed offline earlier.

**Comment by shyamjvs** [comment] 2017-09-05 17:03
@krzyzacy ^

**Comment by shyamjvs** [comment] 2017-09-05 17:07
Fyi - this issue is affecting almost all gke jobs. Though it's a separate issue that they're failing :p

**Comment by shyamjvs** [comment] 2017-09-05 17:15
Reopening.. until this is resolved.

**Comment by shyamjvs** [comment] 2017-09-06 11:09
@krzyzacy I'm seeing that the latest run (196) of https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-cluster-new had run against test-infra commit a90ef48ec, but still seeing the old gke deployer code:

```
W0906 03:41:15.854] export LOG_DUMP_SSH_USER="${USER}"
W0906 03:41:15.854] export LOG_DUMP_SSH_KEY='/workspace/.ssh/google_compute_engine'
```

which should be modified by the push in #4386. Could you PTAL?

**Comment by shyamjvs** [comment] 2017-09-06 11:20
I also verified that we're using the new image for the job.
Can you confirm that your image build went through fine?

**Comment by krzyzacy** [comment] 2017-09-06 16:53
196 started before I merge #4386, can you check 197/198? (198 looks busted)

**Comment by ericchiang** [comment] 2017-09-06 16:58
@krzyzacy 197 doesn't have the expected logs http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-new/197/

**Comment by krzyzacy** [comment] 2017-09-06 17:12
@shyamjvs from 197 I saw
```
error during bash -c 
function log_dump_custom_get_instances() {
  if [[ $1 == "master" ]]; then
    return 0
  fi

  gcloud compute instances list '--project=gke-up-c1-4-glat-up-mas' '--filter=(metadata.created-by:*zones/us-central1-a/instanceGroupManagers/gke-bootstrap-e2e-default-pool-a63f4af8-grp)' '--format=get(name)'
}
export -f log_dump_custom_get_instances
# Set below vars that log-dump.sh expects in order to use scp with gcloud.
export PROJECT=gke-up-c1-4-glat-up-mas
export ZONE='us-central1-a'
export KUBERNETES_PROVIDER=gke
./cluster/log-dump/log-dump.sh '/workspace/_artifacts'
: exit status 1
```

**Comment by krzyzacy** [comment] 2017-09-06 17:40
cc @zmerlynn who wrote the gke deployer and might know better

**Comment by shyamjvs** [comment] 2017-09-06 17:48
@krzyzacy @ericchiang Since this is an upgrade test.. maybe we need to cherry-pick my change (kubernetes/kubernetes#51834) to the corresponding earlier branches. Wdyt?

**Comment by zmerlynn** [comment] 2017-09-06 17:50
It's still getting "I0906 12:43:27.914] LOG_DUMP_SSH_KEY not set, but
required when using log_dump_custom_get_instances" even after the last PR

**Comment by shyamjvs** [comment] 2017-09-06 17:56
Since we're explicitly setting `KUBERNETES_PROVIDER=gke` here - https://github.com/kubernetes/test-infra/blob/master/kubetest/gke.go#L313
we shouldn't enter that condition in the if else chain in log-dump.sh.

Smells like it's using an earlier release branch.
@ericchiang If you can confirm this, I can send out a cherry-pick PR to the concerned branch.

**Comment by ericchiang** [comment] 2017-09-06 18:05
@shyamjvs I can confirm that those changes will need to be cherry picked. Don't know what the exact roll out process is though.

**Comment by ericchiang** [comment] 2017-09-08 15:41
Now that https://github.com/kubernetes/kubernetes/pull/52056 is cherry picked what's the next steps?

**Comment by ericchiang** [comment] 2017-09-12 17:42
Any updates on this? We're still having a lot of issues debugging any of the upgrade test failures.

cc @kubernetes/kubernetes-release-managers

**Comment by krzyzacy** [comment] 2017-09-12 18:25
looks like only gke upgrade tests are missing logs?

@zmerlynn can it be related to now that we are using [gkeLogDumpTemplate](https://github.com/kubernetes/test-infra/blob/1d8efcbc588c5448ee30a1a250e062626006d54d/kubetest/gke.go#L308-L322), or gcloud might mess up with --filter flag again?

**Comment by shyamjvs** [comment] 2017-09-12 18:27
@ericchiang Sorry I've been busy with some scalability-related issues of the release. I'll try taking a look into this today.
@zmerlynn Might have context here.

**Comment by shyamjvs** [comment] 2017-09-12 18:30
@krzyzacy This doesn't seem to be an issue only with upgrade tests.. I'm not seeing logs even for the regular gke job - http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke/14390/artifacts/

**Comment by krzyzacy** [comment] 2017-09-12 18:33
@shyamjvs yeah, figured. I saw
```
WARNING: --filter : operator evaluation is changing for consistency across Google APIs.  metadata."created-by":*zones/us-central1-b/instanceGroupManagers/gke-e2e-2211-default-pool-e4166570-grp currently matches but will not match in the near future.  Run `gcloud topic filters` for details.
```
Maybe the `--filter` flag changed behavior again in gcloud, I'll take a look

**Comment by shyamjvs** [comment] 2017-09-12 18:33
Btw - I'm seeing the following logs from log-dump.sh script:

```
I0912 17:56:49.072] Dumping logs for nodes provided by log_dump_custom_get_instances() function
W0912 17:56:56.485] WARNING: --filter : operator evaluation is changing for consistency across Google APIs.  metadata."created-by":*zones/us-central1-f/instanceGroupManagers/gke-bootstrap-e2e-default-pool-7de11aae-grp currently matches but will not match in the near future.  Run `gcloud topic filters` for details.
<and then the step finishes>
```

**Comment by shyamjvs** [comment] 2017-09-12 18:34
Yup... Seems like an issue with the filter flag. We're still using gcloud 163.0.0 right?

**Comment by krzyzacy** [comment] 2017-09-12 18:35
for gke, most of them uses `"--gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging",` (which is known bad), maybe we can pin gke jobs to 163.0.0 as well, but we still want to fix the actual issue..

**Comment by krzyzacy** [comment] 2017-09-12 18:36
Guess I'll switch the gcloud version for gke-canary job see if that will be fixed to start with.

**Comment by shyamjvs** [comment] 2017-09-12 18:53
Canary sounds fine.. But we should be careful about pinning gcloud to an older one as I think some of our jobs depend on new gcloud api (for e.g regional - @wojtek-t would be able confirm).

**Comment by krzyzacy** [comment] 2017-09-12 18:58
https://github.com/kubernetes/kubernetes/issues/49673 is closed recently, we might be able to unpin the gcloud version.

I'm not sure why all gke jobs uses gcloud from ci/staging bucket, @zmerlynn or @roberthbailey  might know more?

I'll also try to make a fix to the --filter flag.

**Comment by shyamjvs** [comment] 2017-09-12 19:33
We should be unpinning to use the latest one instead of trying to put up with an ancient gcloud. It's getting increasingly hard to maintain this.
@ixdy Is the migration to newer flags done? Or something's still blocking from unpinning?

**Comment by krzyzacy** [comment] 2017-09-12 19:51
I'll unpin it and see if it breaks anything.

**Comment by abgworrall** [comment] 2017-09-12 20:03
Github needs a `For Science !` emoji thing :)

**Comment by shyamjvs** [comment] 2017-09-12 20:08
Ok, I just checked locally by running the command (against gcloud 169.0.0 which is pretty new) and it seems to work though the warning is printed:

```
$ nodes=$(gcloud compute instances list --project k8s-scale-testing '--filter=(metadata.created-by:*zones/us-east1-a/instanceGroupManagers/gke-cluster-1-default-pool-c9471aa4-grp)' '--format=get(name)')
WARNING: --filter : operator evaluation is changing for consistency across Google APIs.  metadata."created-by":*zones/us-east1-a/instanceGroupManagers/gke-cluster-1-default-pool-c9471aa4-grp currently matches but will not match in the near future.  Run `gcloud topics filters` for details.
$
$ echo $nodes
gke-cluster-1-default-pool-c9471aa4-08sz gke-cluster-1-default-pool-c9471aa4-15t5 .....
```

The problem is likely somewhere inside log-dump.sh. WIll add some debugging statements there.

**Comment by ixdy** [comment] 2017-09-12 20:12
Let's take the filter warning to kubernetes/kubernetes#49673.

**Comment by krzyzacy** [comment] 2017-09-12 20:13
yeah - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-canary/2214?log#log gets rid of the warning but still not feel like to dump anything :-(

**Comment by shyamjvs** [comment] 2017-09-12 20:53
I've got a working fix for this that I tested locally - I'll send out a PR for it.

**Comment by zmerlynn** [comment] 2017-09-12 21:42
Isn't this actually broken because of the change back to names and not IPs? This was working for me with IPs and I accepted the other change, but I'm not sure it's right.

**Comment by zmerlynn** [comment] 2017-09-12 21:53
(I think the issue here, if you wind back to the state I had the GKE deployer at 3 weeks ago, is that the `LOG_DUMP_SSH_KEY` isn't getting set correctly, but they need to be IPs to contemplate ssh working at all.)

**Comment by shyamjvs** [comment] 2017-09-12 22:00
There were 2 issues with using IPs:
- It makes it really hard to look for a particular node (as all you see is a bunch of IPs)
- This doesn't work with logexporter which matches the names of the instances against the names of kubernetes node objects

**Comment by zmerlynn** [comment] 2017-09-12 22:00
Yes, but ... it was working. :)

**Comment by shyamjvs** [comment] 2017-09-12 22:02
It wasn't working with logexporter. And IMO IPs just looks weird - we should try to be consistent with GCE (where we're using the actual node names).

**Comment by zmerlynn** [comment] 2017-09-12 22:03
The state that #52360 leaves log-dump for GKE in makes it completely indecipherable, unfortunately. It was only barely decipherable before.

**Closed** 2017-09-13 04:45 UTC
