### ISSUE TITLE
Prow issue: openshift-ci bot: /cc doesn't handle `-` in user names

### ISSUE THREAD

**Issue by jan--f** [kubernetes/test-infra#29999] opened 2023-07-04 08:07 UTC
The ci bot responded to a list of `/cc` commands in [this comment](https://github.com/openshift/enhancements/pull/1434#issuecomment-1614706241). All usernames with one or more `-` in it where truncated at the first `-` and unrelated people got mentioned.

**Comment by smg247** [comment] 2023-07-06 16:50
This isn't specific to openshift, and would be a bug fix in the "assign" plugin.

/sig testing
/area prow

**Comment by smg247** [comment] 2023-07-06 20:03
It appears that it can handle `-`'s in the login name: https://github.com/openshift/enhancements/pull/1434#issuecomment-1624241863. That makes the root of the issue with the original comment even more confusing...

**Comment by smg247** [comment] 2023-07-06 20:09
Digging through logs presents the actual error encountered on the original attempt:
```
Failed to add reviewer(s) to openshift/enhancements#1434: could not request a PR review from the following user(s): s, bear, jan, mike; status code 422 not one of [201], body: {"message":"Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the openshift/enhancements repository.","documentation_url":"https://docs.github.com/rest/reference/pulls#request-reviewers-for-a-pull-request"}.
```

**Comment by smg247** [comment] 2023-07-06 20:23
Interestingly, the failure [comment](https://github.com/openshift/enhancements/pull/1434#issuecomment-1614706241) from the bot has also trimmed the logins off at the `-`:

> /cc @2uasimojo
/cc @bear
/cc @bn222
/cc @bradmwilliams
/cc @coreydaley
/cc @coverprice
/cc @cybertron
/cc @dougbtv
/cc @dry923
/cc @dulek
/cc @flavianmissi
/cc @hasbro17
/cc @jan
/cc @jaypoulz
/cc @jeffdyoung
/cc @jmguzik
/cc @jotak
/cc @lmzuccarelli
/cc @LorbusChris
/cc @mike
/cc @moadz
/cc @pavolloffay
/cc @rphillips
/cc @s
/cc @sinnykumari
/cc @stlaz
/cc @syed
/cc @tkashem
/cc @travier
/cc @TrilokGeer
/cc @trozet

This comes directly from the comment that github sends Prow via webhook. I think prow may have just received an incorrectly formatted comment from the github webhook. It will be interesting to see if anyone can reproduce this as I cannot.

**Comment by 2uasimojo** [comment] 2023-07-06 20:32
Tagging @dhellmann to confirm, but I think the original version of the [comment](https://github.com/openshift/enhancements/pull/1434#issuecomment-1614703858) had the truncated names due to an [error in the script](https://github.com/openshift/enhancements/pull/1434#issuecomment-1621727344) that generated the list. I think test-infra did what it was supposed to (unless you want to take issue with the fact that it didn't /cc the users once the comment was edited to fix their handles).

**Comment by smg247** [comment] 2023-07-06 20:33
> Tagging @dhellmann to confirm, but I think the original version of the [comment](https://github.com/openshift/enhancements/pull/1434#issuecomment-1614703858) had the truncated names due to an [error in the script](https://github.com/openshift/enhancements/pull/1434#issuecomment-1621727344) that generated the list. I think test-infra did what it was supposed to (unless you want to take issue with the fact that it didn't /cc the users once the comment was edited to fix their handles).

Oh...I didn't catch that the comment was edited! Yes, that is certainly the cause here. This is expected behavior.

/close

**Closed by smg247** 2023-07-06 20:33 UTC
Labels: area/prow, sig/testing

**Comment by dhellmann** [comment] 2023-07-06 20:38
Yes, sorry, the bot didn't submit that comment. I had a buggy script that I used to produce it and I pasted the output in by hand.

**Comment by smg247** [comment] 2023-07-06 20:43
And I inadvertently tagged everyone again here. I didn't realize it would do that if it was part of a quote. Sorry about that.
