### ISSUE TITLE
"/ok-to-test" is not respected when it's inline review comment.

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#7801] opened 2018-04-20 02:56 UTC
See: https://github.com/kubernetes/kubernetes/pull/62850#discussion_r182933346

CI tests aren't triggered.

cc @BenTheElder @cjwagner

**Comment by BenTheElder** [comment] 2018-04-20 03:08
Yeah, I consider this a bug as well. See the discussion here for more on options for handling this (not decided yet) https://github.com/kubernetes/test-infra/issues/3827

Closing as a dupe of #3827 
/close

**Closed by BenTheElder** 2018-04-20 03:08 UTC

**Comment by xiangpengzhao** [comment] 2018-04-20 04:00
Thanks @BenTheElder ! I forgot that thread when creating this :)
