### ISSUE TITLE
bot isn't suggesting approvers

### ISSUE THREAD

**Issue by liggitt** [kubernetes/test-infra#2331] opened 2017-03-24 16:19 UTC
Seen at https://github.com/kubernetes/kubernetes/pull/43609#issuecomment-288942444

Bot submits a "needs approval" comment without @ mentioning any particular approver

```
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/kubernetes/kubernetes/pull/43609#" title="Author self-approved">Random-Liu</a>*
We suggest the following additional approvers: 

<details open>
Needs approval from an approver in each of these OWNERS Files:

- **[cluster/OWNERS](https://github.com/kubernetes/kubernetes/blob/master/cluster/OWNERS)**

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={approvers:[]} -->
```

**Comment by apelisse** [comment] 2017-03-24 21:34
Ack, I can reproduce and found the reason why that happens. Working on a fix.

**Comment by apelisse** [comment] 2017-04-05 21:00
Should be fixed now

**Closed by apelisse** 2017-04-05 21:00 UTC
Labels: area/mungegithub
