### ISSUE TITLE
k8s-infra-gcr-vuln-dashboard service account not found

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#19326] opened 2020-09-23 17:48 UTC
```
jsonPayload: {
  component: "prow-controller-manager"   
  error: "pods "15ff72de-fdc0-11ea-bf6c-a2eeca28ab84" is forbidden: error looking up service account test-pods/k8s-infra-gcr-vuln-dashboard: serviceaccount "k8s-infra-gcr-vuln-dashboard" not found"   
  file: "prow/plank/reconciler.go:468"   
  func: "k8s.io/test-infra/prow/plank.(*reconciler).syncTriggeredJob"   
  job: "ci-k8sio-vuln-dashboard-update"   
  level: "warning"   
  msg: "Unprocessable pod."   
 }
```

**Comment by cjwagner** [comment] 2020-10-09 17:39
/assign yodahekinsew
This error appears to be caused by the job added in this PR: https://github.com/kubernetes/test-infra/pull/19003

**Comment by cjwagner** [comment] 2020-10-13 18:56
This is still an issue.
/assign @justaugustus @listx

**Comment by spiffxp** [comment] 2020-10-16 18:27
I would recommend moving this job over to k8s-infra-prow-build-trusted (which has this account, ref: https://github.com/kubernetes/k8s.io/blob/master/infra/gcp/clusters/projects/k8s-infra-prow-build-trusted/prow-build-trusted/resources/build-serviceaccounts.yaml#L50-L56)

The job would need to live here https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/wg-k8s-infra/trusted/wg-k8s-infra-trusted.yaml

**Comment by spiffxp** [comment] 2020-10-16 18:27
Also ref: https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/266#issuecomment-710162069

**Comment by justaugustus** [comment] 2020-10-18 00:11
Carlos, please work on this as part of https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/269.

/assign @cpanato 
/unassign

**Closed** 2020-10-22 23:15 UTC
Labels: kind/bug, kind/oncall-hotlist

**Comment by cpanato** [comment] 2020-10-23 07:10
PR is merged, bit the job is failing for another reason now

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-k8sio-vuln-dashboard-update/1319508946259546112

will take a look
