### ISSUE TITLE
test-grid sort by failures doesn't always work

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/test-infra#12804] opened 2019-05-29 22:12 UTC
Example: https://testgrid.k8s.io/istio-postsubmits-master#integration-k8s-tests&sort-by-failures=

There are some failures at the top, then a bunch of green, then more failures at the bottom. This is especially bad because we expect failures at the top and assume all tests pass otherwise, so failures are missed.

I tried on chrome and firefox so I think it isn't a local issue

**Comment by spiffxp** [comment] 2019-08-06 19:54
/area testgrid
/sig testing
/assign @michelle192837 
I believe this was an internal failure mode of testgrid, and think this is now addressed, but assigning to @michelle192837 to confirm

**Comment by michelle192837** [comment] 2019-08-06 20:45
This is known but not addressed yet (I could not find out why on earth it's doing this :/). I think it's actually only on external because the frontend logic handling this is slightly different, but no idea on what the cause of the bug actually is.

**Comment by BenTheElder** [comment] 2019-09-05 03:38
@howardjohn are you still seeing this? I _think_ the latest release fixes this. Worked with Michelle to rewrite the sort.
/assign

**Comment by howardjohn** [comment] 2019-09-05 03:43
Seems to work!

**Comment by michelle192837** [comment] 2019-09-05 16:53
Thanks again Ben for the fix! ^^

**Closed by michelle192837** 2019-09-05 16:53 UTC
Labels: area/testgrid, kind/bug, sig/testing
