### ISSUE TITLE
PR Dashboard: did not remove PR #52067 after it was merged almost a month ago

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/test-infra#5298] opened 2017-11-01 17:56 UTC
The PR was not removed from PR dashboard although it was merged almost a month ago.
https://github.com/kubernetes/kubernetes/pull/52067

**Comment by kargakis** [comment] 2017-11-03 09:43
Dupe of https://github.com/kubernetes/test-infra/issues/4298

**Closed by kargakis** 2017-11-03 09:43 UTC
Labels: area/gubernator, kind/bug
