### ISSUE TITLE
Tide on GitHub=="not mergeable"; Tide's PR status=="Good to be merged"

### ISSUE THREAD

**Issue by Ark-kun** [kubernetes/test-infra#15402] opened 2019-11-26 04:10 UTC
My PR which is "Good to be merged" is not getting merged for many hours. Looks like Tide forgot about it.

Probably related to https://github.com/kubernetes/test-infra/issues/7254

Tide's PR status says "Good to be merged" https://prow.k8s.io/pr?query=is%3Apr+repo%3Akubeflow%2Fpipelines+author%3AArk-kun+head%3ASDK---Client---Fixed-Client-on-Windows---2

GitHub's Tide status is "Pending — Not mergeable." https://github.com/kubeflow/pipelines/pull/2646 

Tide status has nothing for the repo. https://prow.k8s.io/tide

**Comment by stevekuznetsov** [comment] 2019-11-26 04:15
Judging by the [`tide` history](https://prow.k8s.io/tide-history?repo=kubeflow%2Fpipelines&branch=master) something is misconfigured in your branch protection:

```
failed merging [2636]: [PR is unmergable. Do the Tide merge requirements match the GitHub settings for the repo? Required status check "tide" is pending.]
failed merging [2635]: [PR is unmergable. Do the Tide merge requirements match the GitHub settings for the repo? Required status check "Travis CI - Pull Request" is in progress.]
```

**Comment by cjwagner** [comment] 2019-11-26 04:32
ref: https://github.com/kubeflow/pipelines/issues/930, https://github.com/kubeflow/pipelines/issues/1653
"tide" should not be a required status check. The Travis CI GitHub check issue is being actively worked on now.
For now if this happens please `/hold` the PR and reference one of the tracking issues.

**Comment by Bobgy** [comment] 2019-11-26 05:04
> "tide" should not be a required status check.

I don't quite follow. If "tide" is not required, how do we guard against people merging PRs without lgtm and approval labels.
Please correct me if I missed something, my understanding is:
```
failed merging [2635]: [PR is unmergable. Do the Tide merge requirements match the GitHub settings for the repo? Required status check "Travis CI - Pull Request" is in progress.]
```
```
failed merging [2636]: [PR is unmergable. Do the Tide merge requirements match the GitHub settings for the repo? Required status check "tide" is pending.]
```
These two errors are irrelevant. Current symptom is that tide status check is not synced on kubeflow/pipelines repo, therefore merges are blocked. For example: https://github.com/kubeflow/pipelines/pull/2646

**Comment by jingzhang36** [comment] 2019-11-26 15:58
I ran into the same issue on kubeflow/pipelines repo. https://github.com/kubeflow/pipelines/pull/2620 should

**Comment by stevekuznetsov** [comment] 2019-11-26 16:22
> I don't quite follow. If "tide" is not required, how do we guard against people merging PRs without lgtm and approval labels.

In general we do not suggest that contributors have the ability to merge using the GitHub UI _unless_ it is expected that they have the background to circumvent the process. Prow has a set of functionality (like, `/milestone`) that allows users without write access to the repository to be able to use useful GitHub features and be productive. Giving a user the ability to merge on their web UI is not compatible with the current model.

**Comment by Ark-kun** [comment] 2019-11-26 18:32
> Judging by the [`tide` history](https://prow.k8s.io/tide-history?repo=kubeflow%2Fpipelines&branch=master) something is misconfigured in your branch protection:
> 
> ```
> failed merging [2636]: [PR is unmergable. Do the Tide merge requirements match the GitHub settings for the repo? Required status check "tide" is pending.]
> failed merging [2635]: [PR is unmergable. Do the Tide merge requirements match the GitHub settings for the repo? Required status check "Travis CI - Pull Request" is in progress.]
> ```

I know that this happens (sorry about that, we're already migrating), but in this case it wasn't the case. All other checks were green.

Also Travis does not prevent Tide from putting PR into the merge pool.

Please look at @jingzhang36 case - kubeflow/pipelines#2620
It's still live. All checks are green other than Tide.

**Comment by cjwagner** [comment] 2019-11-26 18:52
Tide is ignoring that PR because of a missing status context due to a new job requirement:
```
{
  base-sha: "9ad7d7dd9776ce75a83712f5723db2ef93ba5c26"   
  branch: "master"   
  component: "tide"   
  context: "kubeflow-pipeline-frontend-test"   
  controller: "sync"   
  file: "prow/tide/tide.go:564"   
  func: "k8s.io/test-infra/prow/tide.filterPR"   
  level: "debug"   
  msg: "filtering out PR as unsuccessful context is not pending"   
  org: "kubeflow"   
  pr: 2620   
  repo: "pipelines"   
  sha: "e1ef51d0a79ed443518afdb0cfcb4541b50d5075"   
 }
```
New requirement: https://github.com/kubernetes/test-infra/pull/15381

The Tide status context should have updated to reflect the missing requirement after the PR was commented on after the new requirement went into effect. @stevekuznetsov @alvaroaleman  Any idea why that didn't happen?

**Comment by rmgogogo** [comment] 2019-11-27 00:58
I also run into the issue.

**Comment by Bobgy** [comment] 2019-11-27 02:22
@stevekuznetsov thanks for the explanation! I've updated the repo to change tide to non required.

**Comment by Bobgy** [comment] 2019-11-27 02:27
Did I understand it correctly? Root cause is:
1. I added a new test `kubeflow-pipeline-frontend-test`
2. Old PRs didn't run this test
3. So old PRs cannot be merged
4. However, tide should update the new requirement in its context.

For blocked PRs, we can just /retest or /test kubeflow-pipeline-frontend-test should make sure tide is up-to-date.

**Comment by alvaroaleman** [comment] 2019-11-27 07:33
Well, Tide does know about the new requirement, otherwise the PR would have gotten merged. The `status-reconciler` (if its set up on prow.k8s.io) should create the new job for existing PRs after the new job was added to the configuration. Since the `status-reconciler` is edge-driven thought, that will only happen if it observed the config change.

**Comment by stevekuznetsov** [comment] 2019-11-27 22:26
I would look at the `status-reconciler` logs to see what it did as a response to the config changing.

**Comment by fejta** [comment] 2019-12-05 23:01
/area prow
/area prow/tide
/assign @stevekuznetsov @cjwagner 

Do we need this on the oncall-hotlist? It looks like this is largely a configuration/user error, right? Not a prow outage/regression.

**Comment by cjwagner** [comment] 2019-12-06 01:23
The immediate problem has been worked around, but we haven't debugged why Tide's status controller or the status-reconciler didn't work as expected which could be a regression.

**Comment by Ark-kun** [comment] 2019-12-06 01:35
@cjwagner @fejta 
I have another instance of PR with similar symptoms (but this time, this has nothing to with added presubmit tests).

GitHub: https://github.com/kubeflow/pipelines/pull/2688
Some checks haven’t completed yet
3 expected, 1 pending, and 3 successful checks
* kubeflow-pipeline-e2e-test Expected — Waiting for status to be reported
* kubeflow-pipeline-frontend-test Expected — Waiting for status to be reported
* kubeflow-pipeline-sample-test Expected — Waiting for status to be reported
* tide Pending — Not mergeable.

Tide: Good to be merged https://prow.k8s.io/pr?query=is%3Apr+repo%3Akubeflow%2Fpipelines+author%3AArk-kun+head%3ASDK---Fixed-capitalization-in-_python_function_name_to_component_name

Tide status: nothing for that repo.

**Comment by fejta** [comment] 2019-12-06 05:33
The kubeflow jobs are migrating to prow.gflocks.com. Has that finished? Any chance it's related?

**Comment by stevekuznetsov** [comment] 2019-12-06 19:09
@Ark-kun that looks like you have jobs still configured in the branch protection for the branch but they are not configured in Prow and have not been triggered.

**Closed** 2020-01-16 22:48 UTC
Labels: area/prow, area/prow/tide, kind/bug, kind/oncall-hotlist

**Comment by hzxuzhonghu** [comment] 2020-07-14 11:20
I meet the similar error:

```
 "Error":"failed merging [918]: [PR is unmergable. Do the Tide merge requirements match the GitHub settings for the repo? Required status check "Travis CI - Pull Request" is in progress.]"
    }
```

https://github.com/volcano-sh/volcano/pull/929

Any help is appreciated.

**Comment by cjwagner** [comment] 2020-07-14 16:41
@hzxuzhonghu GitHub checks are not supported by Tide, only status contexts that appear near the merge button (not the checks tab). See the issues referenced here for more info: https://github.com/kubernetes/test-infra/issues/15402#issuecomment-558455123

**Comment by hzxuzhonghu** [comment] 2020-07-15 02:15
@cjwagner Sorry, i can not catch up, what do you mean ` GitHub checks`

**Comment by petr-muller** [comment] 2020-07-15 09:07
@hzxuzhonghu This doc should help about the difference between statuses and checks: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-status-checks#types-of-status-checks-on-github
