### ISSUE TITLE
PR Dashboard: Outgoing shows merged PRs

### ISSUE THREAD

**Issue by mml** [kubernetes/test-infra#4318] opened 2017-09-01 17:14 UTC
kubernetes/kubernetes#51649 merged 9 hours ago.

![wurmdbtv9vx](https://user-images.githubusercontent.com/3115/29980324-313cedce-8efe-11e7-8d03-0325e8c20dfd.png)

**Comment by kargakis** [comment] 2017-09-02 12:37
Dupe of https://github.com/kubernetes/test-infra/issues/4298

**Closed by kargakis** 2017-09-02 12:37 UTC
