### ISSUE TITLE
Running update owners does not clear the auto-assigned field

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#956] opened 2016-10-29 19:21 UTC
See for example https://github.com/kubernetes/kubernetes/pull/35673/files where Caesar is adding himself as an owner, but it still says auto-assigned is true

**Comment by rmmh** [comment] 2016-11-01 17:15
I'm really not sure what happened here. I can't reproduce this behavior by running the script on Linux or OSX.

 @caesarxuchao might have more details.

**Comment by caesarxuchao** [comment] 2016-11-01 17:25
I ran the script with `update_owners.py --user=caesarxuchao", is that correct?

(@fejta you can call me Chao :)

**Comment by rmmh** [comment] 2016-11-01 17:33
Ahh, the update_owners.py script was outdated on the branch!

https://github.com/caesarxuchao/kubernetes/blob/7818d8bc1aeb2fcff4de444bd1b454a4a6789203/hack/update_owners.py#L171

It's hard to see in the final commit because a later rebase and force push erased it from the publicly visible history.

This should resolve itself naturally as older branches are merged or rebased. I'll audit the test_owners.csv changes next week to see if there's any other weirdness that slipped through.

**Closed** 2016-11-01 17:36 UTC
