### ISSUE TITLE
milestones should rank higher in the submit queue

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#1201] opened 2016-11-28 19:57 UTC
For example if we have 2 PR(s) with ["P3","v1.5"] or ["P2","v1.6"] 

Currently we are prioritizing the 1.6 above the 1.5... Can we please do the opposite?

**Comment by dims** [comment] 2016-11-28 19:57
cc @saad-ali @rmmh

**Comment by saad-ali** [comment] 2016-11-28 19:59
http://submit-queue.k8s.io/#/info Looks like "by design" the priority labels take precedence over milestone. We should change that. In the mean time we can manually bump the priority of 1.5 PRs

**Comment by rmmh** [comment] 2016-11-28 20:03
Changing this might be a little tricky. In this case we want the 1.5 PRs to have higher priority, but if we change the logic in a simple way, just labelling your PR with *any* milestone will cause it to be treated as more important than a P0 issue.

**Comment by rmmh** [comment] 2016-11-28 20:20
Duplicate of kubernetes/contrib#2083.

**Closed by rmmh** 2016-11-28 20:20 UTC
