### ISSUE TITLE
Continuous bot spam when cherry-pick parent PR does not have valid release note label

### ISSUE THREAD

**Issue by eparis** [kubernetes/test-infra#4431] opened 2017-09-07 00:58 UTC
https://github.com/kubernetes/kubernetes/pull/52056

Was getting spammed multiple times per minute with the same message.
```
The 'parent' PR of a cherry-pick PR must have one of the "release-note" or "release-note-action-required" labels, or this PR must follow the standard/parent release note labeling requirement.
```
Both the parent PR and the reference PR had `release-note-none` set. So the process WAS being followed.

The bot was nice enough to delete the old comment every time it posted a new comment. which is why all of the spam can't be seen in the PR anymore.

**Comment by cjwagner** [comment] 2017-09-21 01:55
/assign
This issue is a duplicate of #4523  
This was fixed in #4530

**Closed** 2017-09-21 01:55 UTC
Labels: area/mungegithub
