### ISSUE TITLE
gubernator reporting incorrectly 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/test-infra#1786] opened 2017-02-03 15:29 UTC
Gubernator is incorrectly reporting information (https://k8s-gubernator.appspot.com/pr) user `timothysc` This is true for other folks as well.  

e.g. - it says https://github.com/kubernetes/kubernetes/pull/40735 "Needs Attention" 

When is was merged a while ago. 

/cc @jayunit100

**Comment by spxtr** [comment] 2017-02-03 18:15
Probably dropped the webhook. @rmmh

**Comment by rmmh** [comment] 2017-02-03 22:59
dupe of #1576

**Closed by rmmh** 2017-02-03 22:59 UTC
Labels: gubernator
