### ISSUE TITLE
Enable CSIMigration Feature Gate on AllAlpha clusters when migrated drivers installed by default

### ISSUE THREAD

**Issue by davidz627** [kubernetes/test-infra#11202] opened 2019-02-08 21:05 UTC
**What should be cleaned up or changed**:
Remove all instances of `CSIMigration=false` when `AllAlpha=true` specified in test jobs when we are installing CSI Drivers by default.

**Provide any links for context**:
Migration feature is tracked here: https://github.com/kubernetes/enhancements/issues/625
Driver installation feature is being designed.

**Comment by nzoueidi** [comment] 2019-02-14 18:03
I suppose while the PR #11201 got merged, this issue need to be closed.

**Comment by davidz627** [comment] 2019-02-14 19:02
@nzoueidi unfortunately no, that PR was *disabling* the feature gate. This issue is to *enable* the feature gate when we have "CSI Driver Installation."

**Comment by davidz627** [comment] 2019-05-16 01:55
/remove-lifecycle stale
/lifecycle frozen
revisit in k8s 1.17

**Comment by liggitt** [comment] 2019-11-08 18:12
note that we should only enable the feature in versions in which our setup scripts actually set up the drivers

**Comment by jayaddison** [comment] 2019-12-11 19:41
@liggitt @davidz627 Hopefully this is a rare case, and apologies if I'm not reporting this in the ideal place - I wanted to note that another user and myself hit issues after upgrading to `1.17` in https://github.com/kubernetes/kubernetes/issues/86094 which relate to `CSINode` resources and the `CSIMigration` feature gate.

My concern is that other people might experience the same issue, and that it might not have been discovered during testing since the gate is disabled in `test-infra` (for good reason, but also perhaps accidentally hiding the upgrade issue).

Do you know if there's another group we could/should mention this to?  Or perhaps a way to confirm that it's a non-issue / edge case?

**Comment by liggitt** [comment] 2019-12-11 20:03
@jayaddison looking at that issue, it appears that the root cause was a 1.17 kubelet trying to run against a 1.16 API server. Is that correct?

**Comment by liggitt** [comment] 2019-12-11 20:05
> it might not have been discovered during testing since the gate is disabled in `test-infra`

The majority of our CI jobs do not disable that gate, and run successfully.

**Comment by jayaddison** [comment] 2019-12-11 20:45
@liggitt Excellent - yep; I left a note in that issue too, but just for transparency here, it does seem like it was a case where the API server hadn't been upgraded and was still on `1.16` vs a `1.17` kubelet.  Thanks for clarifying re: the partial disable of the flag in `infra-test` too.

**Comment by dims** [comment] 2024-02-10 02:29
been too long :)

/close

**Closed by dims** 2024-02-10 02:29 UTC
Labels: sig/storage, lifecycle/frozen, kind/cleanup
