### ISSUE TITLE
PR Dashboard: Merged PR still shows up

### ISSUE THREAD

**Issue by dmmcquay** [kubernetes/test-infra#1872] opened 2017-02-10 19:03 UTC
This PR (https://github.com/kubernetes/kubernetes/pull/40045) got merged and still shows up in my PR Dashboard.  Can't seem to make it go away.

**Comment by spxtr** [comment] 2017-02-10 19:06
Likely dupe of #1576.

**Comment by fejta** [comment] 2017-04-09 23:43
Make a comment on the PR and it should go away

**Closed by fejta** 2017-04-09 23:43 UTC
Labels: gubernator
