### ISSUE TITLE
metrics-bigquery job failing since 2020-07-10

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#18393] opened 2020-07-20 22:05 UTC
**What happened**:
https://k8s-testgrid.appspot.com/sig-testing-misc#metrics-bigquery is red

Looks like `bq` is complaining, I think `<LAST_DATA_TIME>` isn't being replaced in the queries we're giving it

**What you expected to happen**:

For the job to be green and results to be produced

**Please provide links to example occurrences, if any**:
See latest failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/metrics-bigquery/1285038502559354882

**Anything else we need to know?**:
I think we removed too much in https://github.com/kubernetes/test-infra/pull/18203

/area metrics
/assign @MushuEE

**Comment by MushuEE** [comment] 2020-07-20 23:01
Should be fixed with reverting #18394, looking into root cause.

**Comment by MushuEE** [comment] 2020-07-21 00:06
Is there no way to force trigger a job?

**Comment by spiffxp** [comment] 2020-07-22 23:56
/close
Passing again https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/metrics-bigquery/1285763628493967361

**Closed** 2020-07-22 23:56 UTC
Labels: area/metrics, kind/bug
