### ISSUE TITLE
Terminate all other batch jobs if one job failed

### ISSUE THREAD

**Issue by luxas** [kubernetes/test-infra#4137] opened 2017-08-21 16:29 UTC
I don't know if this actually is the case or if there is an other issue to track this, but I noticed that the batch jobs in https://prow.k8s.io/?type=batch just continued to run; although two jobs flaked really early on.

Shouldn't we just terminate all the others, quickly recycle things and move on to the next batch in that case? Would be an useful improvement I think

cc @spiffxp @fejta @rmmh @ixdy

**Comment by spxtr** [comment] 2017-08-21 17:59
/area prow

It's a good idea, but we have a problem where if we terminate an e2e job it will leak the cluster.

**Comment by luxas** [comment] 2017-08-21 18:11
@spxtr How easy is it to automatically GC those clusters?

**Comment by kargakis** [comment] 2017-08-21 18:37
Dupe of https://github.com/kubernetes/test-infra/issues/4015

**Closed by kargakis** 2017-08-21 18:37 UTC
Labels: area/prow

**Comment by krzyzacy** [comment] 2017-08-21 18:46
@luxas boskos can handle GC like this case better, so once we split up build/test, and move all actual pr-test jobs to prow, this will be more viable.
