### ISSUE TITLE
peribolos: expired/failed invitations are treated as active

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#21140] opened 2021-03-03 21:31 UTC
When a user's invitation to join an org is expired (they have seven days to accept it), the invitation becomes failed. `peribolos` today treats this as if the invitation were active, and continues to "wait" for the user to accept it. Ideally we'd re-send it.

/area prow/peribolos

**Comment by alvaroaleman** [comment] 2021-03-04 03:54
Duplicate of https://github.com/kubernetes/test-infra/issues/20872
/close

**Closed** 2021-03-04 03:54 UTC
Labels: area/prow/peribolos, kind/bug
