### ISSUE TITLE
gcsupload completes successfully but artifacts are missing

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#7255] opened 2018-03-13 20:20 UTC
Moved from https://github.com/openshift/aos-cd-jobs/issues/1173 + https://github.com/openshift/test-infra/issues/130 for greater visibility

@stevekuznetsov @smarterclayton

**Comment by stevekuznetsov** [comment] 2018-03-15 19:06
Dupe of #7222 

/close

**Closed by stevekuznetsov** 2018-03-15 19:06 UTC
