### ISSUE TITLE
Kind jobs should not immediately kill the cluster on termination before dumping logs

### ISSUE THREAD

**Issue by aojea** [kubernetes/test-infra#26953] opened 2022-07-28 09:10 UTC
> the info is there, but the failing jobs doesn't have it because the job times out cleaning the kind cluster and the related logs

that is itself a bug, and shouldn't be happening. we should get and handle a TERM from prow well before we get killed and the TERM handler should be capturing logs.

_Originally posted by @BenTheElder in https://github.com/kubernetes/kubernetes/issues/111086#issuecomment-1195791252_

**Comment by BenTheElder** [comment] 2022-07-28 17:19
Need to track down an example run where this happened.

**Comment by BenTheElder** [comment] 2022-07-28 17:26
I think there's a race with the cleanup handlers ... fun ... the dind wrapper.sh in the CI image will start cleaning up docker in docker on TERM, but at the same time we are passing it through to the child process and the child process is the e2e script is then doing the capture logs etc.

The problem is we only have one signal before we are forcibly killed, and we don't have synchronization between the layers.

So far I only have examples of it working fine however, like this:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111091/pull-kubernetes-e2e-kind/1549382681064640512

->

```
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:165","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 1h0m0s timeout","severity":"error","time":"2022-07-19T14:18:32Z"}
wrapper.sh] [EARLY EXIT] Interrupted, entering handler ...
+ wrapper.sh] [CLEANUP] Cleaning up after Docker in Docker ...
signal_handler
+ [ -n 82068 ]
+ kill -TERM 82068
+ cleanup
+ [ false = true ]
+ [ true = true ]
+ kind export logs /logs/artifacts
Exporting logs for cluster "kind" to:
/logs/artifacts
```

And then later:
```
Ginkgo ran 1 suite in 43m48.784055654s
Test Suite Failed
Program process in pidfile '/var/run/docker-ssd.pid', 1 process(es), refused to die.
wrapper.sh] [CLEANUP] Done cleaning up after Docker in Docker.
wrapper.sh] [EARLY EXIT] Completed handler ...
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:252","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process gracefully exited before 15m0s grace period","severity":"error","time":"2022-07-19T14:18:54Z"}
```

@msau42 do you have an example where we failed to collect the logs? I haven't found one in the linked issue yet.

**Comment by BenTheElder** [comment] 2022-07-28 17:28
Sorry, nevermind, that example has this issue, all pod logs are missing. Normally we'd have those, like this: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/111334/pull-kubernetes-e2e-kind-ipv6/1550310688029675520/artifacts/kind-control-plane/

**Comment by msau42** [comment] 2022-07-28 23:12
You can try my pr: https://github.com/kubernetes/kubernetes/pull/111334

**Comment by BenTheElder** [comment] 2022-07-28 23:52
we should just wait for the child process after we signal it, probably more ideal would be to do that with a time limit but this is probably good enough for now https://github.com/kubernetes/test-infra/pull/26963

**Comment by BenTheElder** [comment] 2022-07-29 18:12
should verify the fix before closing

**Comment by BenTheElder** [comment] 2022-07-29 18:41
will test after https://github.com/kubernetes/test-infra/pull/26971

**Comment by BenTheElder** [comment] 2022-07-30 01:22
Fixed, confirmed with a test PR that just hangs the tests indefinitely with `for { time.Sleep() }` https://github.com/kubernetes/kubernetes/pull/111552

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111552/pull-kubernetes-e2e-kind/1553117127823593472

```
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:165","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 1h0m0s timeout","severity":"error","time":"2022-07-29T21:38:30Z"}
wrapper.sh] [EARLY EXIT] Interrupted, entering handler ...
+ signal_handler
+ [ -n 83050 ]
+ kill -TERM 83050
+ cleanup
+ [ false = true ]
+ [ true = true ]
+ kind export logs /logs/artifacts
Exporting logs for cluster "kind" to:
/logs/artifacts
+ kind delete cluster
Deleting cluster "kind" ...
+ rm -f _output/bin/e2e.test
+ [ -n /tmp/tmp.yGlGGxOk9t ]
+ rm -rf /tmp/tmp.yGlGGxOk9t
+ CLEANED_UP=true
+ res=143
+ cleanup
+ [ true = true ]
+ return
+ exit 143
wrapper.sh] [EARLY EXIT] Exit code was 143, not preserving due to interrupt signal
wrapper.sh] [CLEANUP] Cleaning up after Docker in Docker ...
687d2f7f60d5
Stopping Docker: dockerProgram process in pidfile '/var/run/docker-ssd.pid', 1 process(es), refused to die.
wrapper.sh] [CLEANUP] Done cleaning up after Docker in Docker.
wrapper.sh] [EARLY EXIT] Completed handler ...
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:255","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 15m0s grace period","severity":"error","time":"2022-07-29T21:53:30Z"}
{"component":"entrypoint","error":"os: process already finished","file":"k8s.io/test-infra/prow/entrypoint/run.go:257","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Could not kill process after grace period","severity":"error","time":"2022-07-29T21:53:30Z"}
```

TODO: should get around to improving how we run dind ... that's a different issue though.

**Closed by BenTheElder** 2022-07-30 01:22 UTC
Labels: sig/testing
