### ISSUE TITLE
pull-kubernetes-e2e-gce Job is failing due to some error setting test environment.

### ISSUE THREAD

**Issue by paulsubrata55** [kubernetes/test-infra#11946] opened 2019-03-26 14:26 UTC
**What happened**:
Kubernetes Pull request mandatory test `pull-kubernetes-e2e-gce` is failing due to some internal error.

**What you expected to happen**:
pull-kubernetes-e2e-gce should not fail due to some internal script exceptions.

**How to reproduce it (as minimally and precisely as possible)**:
Just create a PR at kubernetes github repo. 

**Please provide links to example occurrences, if any**:
https://prow.k8s.io/log?id=73518&job=pull-kubernetes-e2e-gce
```
W0326 14:08:23.825] 2019/03/26 14:08:23 process.go:96: Saved XML output to /workspace/_artifacts/junit_runner.xml.
W0326 14:08:23.826] 2019/03/26 14:08:23 process.go:153: Running: bash -c . hack/lib/version.sh && KUBE_ROOT=. kube::version::get_version_vars && echo "${KUBE_GIT_VERSION-}"
W0326 14:08:24.205] 2019/03/26 14:08:24 process.go:155: Step 'bash -c . hack/lib/version.sh && KUBE_ROOT=. kube::version::get_version_vars && echo "${KUBE_GIT_VERSION-}"' finished in 380.245182ms
W0326 14:08:24.206] 2019/03/26 14:08:24 main.go:308: Something went wrong: failed to prepare test environment: --provider=gce boskos failed to acquire project: Post http://boskos.test-pods.svc.cluster.local./acquire?type=gce-project&state=free&dest=busy&owner=pull-kubernetes-e2e-gce: dial tcp 10.63.250.132:80: i/o timeout
W0326 14:08:24.209] Traceback (most recent call last):
W0326 14:08:24.209]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 764, in <module>
W0326 14:08:24.209]     main(parse_args())
W0326 14:08:24.209]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 615, in main
W0326 14:08:24.209]     mode.start(runner_args)
W0326 14:08:24.210]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 262, in start
W0326 14:08:24.210]     check_env(env, self.command, *args)
W0326 14:08:24.210]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 111, in check_env
W0326 14:08:24.210]     subprocess.check_call(cmd, env=env)
W0326 14:08:24.210]   File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
W0326 14:08:24.210]     raise CalledProcessError(retcode, cmd)
W0326 14:08:24.210] subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--build=bazel', '--stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce', '--up', '--down', '--test', '--provider=gce', '--cluster=e2e-73518-674b9', '--gcp-network=e2e-73518-674b9', '--extract=local', '--gcp-node-image=gci', '--gcp-zone=us-west1-b', '--ginkgo-parallel=30', '--runtime-config=batch/v2alpha1=true', '--test_args=--ginkgo.skip=\\[Slow\\]|\\[Serial\\]|\\[Disruptive\\]|\\[Flaky\\]|\\[Feature:.+\\] --minStartupPods=8', '--timeout=65m')' returned non-zero exit status 1
E0326 14:08:24.222] Command failed
I0326 14:08:24.222] process 537 exited with code 1 after 2.5m
E0326 14:08:24.222] FAIL: pull-kubernetes-e2e-gce
```

**Anything else we need to know?**:
My already approved PR #74341 is blocked due to this.

**Comment by liggitt** [comment] 2019-03-26 14:44
duplicate of https://github.com/kubernetes/test-infra/issues/11944

/close

**Closed by liggitt** 2019-03-26 14:44 UTC
Labels: kind/bug
