### ISSUE TITLE
See logs while build is running

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/test-infra#1235] opened 2016-11-30 18:22 UTC
While a build is running, I don't see any logs (in gubernator). This is a regression from Jenkins, where I could watch the build output in near real time. Clicking the "Load build log" seems to have no effect. Clicking on build-log.txt gives

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>
```

Clicking on artifacts gives a directory listing with started.json.

**Comment by spxtr** [comment] 2016-11-30 18:36
Dupe of #977. We will have it done in the near future, before transitioning all jobs off of Jenkins.

**Closed by spxtr** 2016-11-30 18:36 UTC

**Comment by roberthbailey** [comment] 2016-11-30 18:39
Oh thanks. I searched for existing issues but didn't see that one.
