### ISSUE TITLE
Empty coverage lens

### ISSUE THREAD

**Issue by amwat** [kubernetes/test-infra#21563] opened 2021-03-29 21:54 UTC
**What happened**:
Empty coverage lens

**What you expected to happen**:
Coverage lens shows coverage treemap

**How to reproduce it (as minimally and precisely as possible)**:
already happening live in prow.k8s.io

**Please provide links to example occurrences, if any**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-coverage-unit/1346830331453378560

**Anything else we need to know?**:
I don't have access to prow.k8s.io logs, but this is also happening in other prows
```
{component: deck, file: prow/simplifypath/simplify.go:48, func: k8s.io/test-infra/prow/simplifypath.(*simplifier).Simplify, level: debug, msg: Path not handled. This is a bug, please open an issue against the kubernetes/test-infra repository with this error message., path: /static/spyglass/lens.css}
```

/cc @michelle192837 

fyi @stevekuznetsov @BenTheElder

**Comment by cjwagner** [comment] 2021-03-30 00:47
I think the `simplifypath` errors are only related to metrics so that probably isn't the cause of this problem.
The prow.k8s.io logs don't include anything from the file `prow/spyglass/lenses/coverage/coverage.go` in the past week. The HTML template seems to execute without error, but I did notice this line was missing: https://github.com/kubernetes/test-infra/blob/f7e21a3c18f4f4bbc7ee170675ed53e4544a0632/prow/spyglass/lenses/coverage/template.html#L9

When I inspect the spyglass page I see multiple occurences of the following error in the console (seems like 1 occurrence per spyglass lens on the page).

> ​Uncaught SecurityError: Sandbox access violation: Blocked a frame at "null" from accessing a frame at "https://prow.k8s.io".  The frame requesting access is sandboxed and lacks the "allow-same-origin" flag.

I also see this error, but only on the spyglass page with the coverage lens:

> Uncaught SyntaxError: Cannot use import statement outside a module     script_bundle.min.js:1

This seems like a likely culprit, but I don't know how to find where that import statement would be (`script_bundle.min.js:1` is not very helpful).

**Comment by chaodaiG** [comment] 2021-04-05 20:09
@amwat , do you have a working example?

**Comment by amwat** [comment] 2021-04-05 20:20
the link in the first issue comment still fails for me

**Comment by chaodaiG** [comment] 2021-04-05 20:22
> the link in the first issue comment still fails for me

Same here. Just want to see whether this is failing for all spyglass pages that use coverage lens or just this specific instance

**Comment by amwat** [comment] 2021-04-05 20:25
> Uncaught SyntaxError: Cannot use import statement outside a module script_bundle.min.js:1

yeah that seems to be the culprit (inspect -> reload frame, and it will spit out the same error again)

line 1 in the browser is

```
import {parseCoverage} from "io_k8s_test_infra/gopherage/cmd/html/static/parser";
```

coming from here

https://github.com/kubernetes/test-infra/blob/072c97c8a7ac61205dc54922813ea0bf52847825/prow/spyglass/lenses/coverage/coverage.ts#L18

and 

https://github.com/kubernetes/test-infra/blob/072c97c8a7ac61205dc54922813ea0bf52847825/gopherage/cmd/html/static/parser.ts#L131

best guess is maybe something changed in the way we create the rollup bundle?

https://github.com/kubernetes/test-infra/pull/20824

/cc @fejta

**Comment by amwat** [comment] 2021-04-05 20:26
> Same here. Just want to see whether this is failing for all spyglass pages that use coverage lens or just this specific instance

I'm seeing this in other prows as well

**Comment by BenTheElder** [comment] 2021-04-21 19:33
This is a pretty frustrating regression that makes running coverage testing on prow borderline useless as you can't easily view or access the results.

In the future I would have expected a rollback / revert at least after this became completely nonfunctional.

**Comment by BenTheElder** [comment] 2021-04-21 19:36
https://github.com/kubernetes/test-infra/issues/20751 seems like the most similar issue, I don't see any other changes that jump out yet.

**Comment by alvaroaleman** [comment] 2021-04-21 19:42
/assign @fejta 
I am out when it comes to understanding how bumping a bazel version changed our build process.

**Comment by BenTheElder** [comment] 2021-04-21 19:43
well it looks like we changed `build_bazel_rules_nodejs` in the same process. looking at the release notes over there.

**Comment by BenTheElder** [comment] 2021-04-21 19:56
going from rules_nodejs 0.36.0 to 3.1.0 seems unsurprising as a source of breakage.

this is the only place we are doing an import like `from 'io_k8s_test_infra...`, which seems likely to be related.

**Comment by BenTheElder** [comment] 2021-04-21 20:02
https://github.com/bazelbuild/rules_nodejs/wiki#no-longer-link-the-workspace-root seems like the culprit, under the "Migrating to 2.0" guide.
/assign

**Comment by fejta** [comment] 2021-04-21 21:03
> In the future I would have expected a rollback / revert at least after this became completely nonfunctional.

Totally agree when we discover regressions reasonably close to when they are introduced.

OTOH when a problem is discovered many releases afterwards (like in this case) it is best to just fix the problem -- reverting in this scenario also has risks: various other things in those releases may have been built on top of the problematic initial PR.

**Comment by BenTheElder** [comment] 2021-04-21 21:15
:+1: should be fixed by https://github.com/kubernetes/test-infra/pull/21897 in any case

**Comment by fejta** [comment] 2021-04-21 21:16
Nice, thank you!

**Comment by BenTheElder** [comment] 2021-04-22 20:19
working again: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-coverage-unit/1358664687264206848

**Closed by BenTheElder** 2021-04-22 20:19 UTC
Labels: area/prow, area/prow/spyglass, help wanted, kind/bug
