### ISSUE TITLE
Prometheus Metrics for Robot Commands

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#3700] opened 2017-07-26 14:01 UTC
It would be cool to see Prometheus metrics we could expose through Velodrome for robot commands like `/retest` to see how users (or a specific user) interact with the robots.

/cc @deads2k @eparis

**Comment by spxtr** [comment] 2017-07-26 17:15
Right now that information is stored for a week or so in logs, but we should try to make it public somehow. I agree.

**Comment by kargakis** [comment] 2017-09-13 22:49
Cardinality becomes unreasonably high if we include individual users as an axis in these metrics.

This issue is possibly a dupe of https://github.com/kubernetes/test-infra/issues/2699.

**Comment by stevekuznetsov** [comment] 2018-01-05 17:34
We've got this in Velodrome now, right, @spiffxp ?

**Closed** 2018-03-11 15:02 UTC
Labels: area/metrics, area/mungegithub, area/prow, lifecycle/rotten
