### ISSUE TITLE
Request approval for specific concepts

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/test-infra#13994] opened 2019-08-21 00:02 UTC
It might be nice to, in some cases, have approval for specific concepts like languages ("is my X code readable") or docs ("approve .md files but not code"). Prow's approval plugin could be extended to do this, via something like:

- Have a top-level directory with OWNERS files for concepts 
  - (e.g. `k/t-i/languages/[go|py|ts]/OWNERS`)
- When PRs are sent for approval, or on request (via a slash command?), detect the file extensions touched
- Add a fake file that the approval plugin recognizes as touching the relevant approval directory 
  - (e.g. approval plugin thinks that `k/t-i/languages/go/fakefile` was added)
- Approval assigns/requires an approver from the relevant file

/area prow
/priority/backlog

**Comment by BenTheElder** [comment] 2019-08-22 07:53
> /priority/backlog

/priority backlog

**Comment by stevekuznetsov** [comment] 2019-09-09 10:37
We've seen a large number of teams whose workflows don't nicely fit into the LGTM+approve workflow hit this issue, all with specific subsets of the solution they need ... either they want N approvers, or approvers by "type", or both. It might make sense to fix this in a first-class manner (instead of hacking through files) as part of whatever the issue is that we have to track approvers making bad assumptions (I can't for the life of me find it).

**Comment by stevekuznetsov** [comment] 2019-09-09 10:37
We've seen a large number of teams whose workflows don't nicely fit into the LGTM+approve workflow hit this issue, all with specific subsets of the solution they need ... either they want N approvers, or approvers by "type", or both. It might make sense to fix this in a first-class manner (instead of hacking through files) as part of whatever the issue is that we have to track approvers making bad assumptions (I can't for the life of me find it).

**Comment by nikhita** [comment] 2019-12-09 11:29
/remove-lifecycle stale
xref https://github.com/kubernetes/test-infra/issues/7690

**Comment by spiffxp** [comment] 2020-04-10 16:53
/remove-lifecycle rotten
Just got pinged for another variant of this, product readiness approval ref: https://github.com/kubernetes/enhancements/pull/1620#discussion_r404981719

**Comment by spiffxp** [comment] 2020-04-10 17:07
Another example: ensure someone from sig-instrumentation gets assigned to PRs that change metrics-related code https://github.com/kubernetes/kubernetes/issues/89788

**Comment by spiffxp** [comment] 2020-04-10 17:09
We can't currently use solutions that regex against paths or file types because the approvers plugin doesn't cooperate with filters (ref: https://github.com/kubernetes/test-infra/issues/7690)

**Closed** 2020-09-07 19:05 UTC
Labels: area/prow, kind/feature, lifecycle/rotten, priority/backlog
