### ISSUE TITLE
Failing gci-gce-scalability-1-23 tests

### ISSUE THREAD

**Issue by azylinski** [kubernetes/test-infra#25914] opened 2022-04-08 10:59 UTC
Test ci-kubernetes-e2e-gci-gce-scalability-1-23 has failed 3 times since it last passed at commit/eaf200eb8 (Thu Apr 07 05:00 PDT)

TestGrid Link: https://testgrid.k8s.io/sig-release-1.23-blocking#gce-cos-1.23-scalability-100

Failing test source code: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-release/release-branch-jobs/1.23.yaml#L372-L451

**Comment by mborsz** [comment] 2022-04-08 11:18
Per https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-1-23/1512309408665702400/podinfo.json

the tests are failing due to:

```
"involvedObject": {
				"kind": "Pod",
				"namespace": "test-pods",
				"name": "34cb3e47-b701-11ec-8441-76f4c220a31c",
				"uid": "75e78146-2712-4c87-8b75-bd262ee416f6",
				"apiVersion": "v1",
				"resourceVersion": "806138710"
			},
			"reason": "FailedCreatePodSandBox",
			"message": "(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox \"549c666cf14af2c7f1a035afb0a9140191b7849bc41e7b1823aea76df8667de3\": error getting ClusterInformation: connection is unauthorized: Unauthorized",
			"source": {
				"component": "kubelet",
				"host": "gke-prow-build-pool5-2021092812495606-e8f905a4-cf86"
			},

```

Which seems to be infra issue.

**Comment by fejta** [comment] 2022-04-08 14:46
Looks like the pod is struggling to start in the cluster, nothing obviously misbehaving on prow's end.

This pod runs in a k8s-infra cluster, which prow oncall does not support: https://github.com/kubernetes/test-infra/blob/1a76bd66eda42678652dee90563e7fc02539e8a3/config/jobs/kubernetes/sig-release/release-branch-jobs/1.23.yaml#L379

1) Possibly related (see the scalability k8s-infra chart): https://monitoring.prow.k8s.io/d/wSrfvNxWz/boskos-resource-usage?orgId=1
2) testgrid seems to be green again: https://testgrid.k8s.io/sig-release-1.23-blocking#gce-cos-1.23-scalability-100
3) Please reach out to #sig-k8s-infra on slack for additional ideas about how to debug the cluster if interested.

**Comment by BenTheElder** [comment] 2022-04-19 02:37
@mborsz @ameukam I seem to recall a slack discussion about this?

**Comment by ameukam** [comment] 2022-04-19 02:58
Root cause has been identified in https://github.com/kubernetes/k8s.io/issues/3600. The job is flaky but it's not related to the containerd issue

**Comment by BenTheElder** [comment] 2022-04-19 04:00
I think we can close this and track the remaining infra issue in k8s.io#3600, thanks @ameukam

**Closed by BenTheElder** 2022-04-19 04:00 UTC
Labels: kind/bug, sig/k8s-infra
