### ISSUE TITLE
Support configuring different pod namespaces in plank

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#8862] opened 2018-07-27 08:16 UTC
Plank supports configuring multiple build clusters but all of them are using the [same namespace](https://github.com/kubernetes/test-infra/blob/cb687dcd868f7ccf1b3b8c71c77a7e47465478fa/prow/cmd/plank/main.go#L152) to run pods. We should support configuring the namespace so we can run pods in different namespaces inside the same cluster. 

cc @stevekuznetsov @cjwagner 

/area prow
/kind feature

**Comment by stevekuznetsov** [comment] 2018-07-27 14:31
dupe of #8848 
/close

**Closed by stevekuznetsov** 2018-07-27 14:31 UTC
Labels: area/prow, kind/feature
