### ISSUE TITLE
Confusion between OWNER_ALIAS + APPROVERNOTIFIER

### ISSUE THREAD

**Issue by philips** [kubernetes/test-infra#1701] opened 2017-01-25 06:26 UTC
It is really really difficult with OWNER_ALIAS to know how to get people's attention for an approval because the OWNER_ALIAS doesn't match a real github group:

![screen shot 2017-01-24 at 10 22 46 pm](https://cloud.githubusercontent.com/assets/33544/22280118/aa938cb4-e283-11e6-8db4-05789dd30f47.png)

I know where to read the code in the mungebot and commit history and resolve the OWNER_ALIAS and ping the right people but it is _super_ confusing if you don't know how to do this.

Suggested solutions:

1) Ensure all owner aliases match a real github group
2) Remove owner aliases as a concept because the de-reference makes everything harder
3) Resolve the owner alias in the merge-bot post to give the contributor an actionable contact

My preference personally is to do #2 but I don't know what the thinking was behind OWNER_ALIAS.  @apelisse?

**Comment by philips** [comment] 2017-01-25 06:28
Link to issue: https://github.com/kubernetes/kubernetes/pull/39112#issuecomment-274686535

**Comment by liggitt** [comment] 2017-01-25 06:44
Possibly a dupe of https://github.com/kubernetes/test-infra/issues/1677?

**Comment by philips** [comment] 2017-01-25 17:16
@liggitt Yes, a dupe of #1677 but I think this illustrates the problem.

cc @calebamiles

**Comment by apelisse** [comment] 2017-01-25 17:18
Closing #1677 in favor of this issue, which better illustrates the problem indeed.

Thanks @philips

**Comment by calebamiles** [comment] 2017-01-25 17:58
@philips, @grodrigues3 is thinking about this issue. Would a comment that linked to 
https://github.com/kubernetes/kubernetes/blob/master/OWNERS_ALIASES

along with having the bot suggest pinging a properly created github group solve your immediate concerns? (option 1)

**Comment by apelisse** [comment] 2017-01-25 18:00
I vote for option 3. We can have the bot resolve the alias before doing anything else. That is, replace the list name by the actual list and then pick someone from this list.

**Comment by philips** [comment] 2017-01-25 19:19
@apelisse That is a workable solution to me. I can't actually find the code that handles OWNERS_ALIAS resolution, I might be dense but can you link to it?

My other concern about OWNERS_ALIAS is that it makes it hard for users to interpret the OWNERS files directly and I don't understand how it interacts with the tools to add reviewers which seems based on peoples experience in certain packages. While OWNERS_ALIAS sort of is meta and allows for people to bypass that pkg view of ownership.

**Comment by apelisse** [comment] 2017-01-25 21:07
The code lives here: https://github.com/kubernetes/test-infra/blob/master/mungegithub/features/aliases.go

I think @grodrigues3 will work on it soon, and I will if he doesn't.

**Closed** 2017-01-26 02:25 UTC
