### ISSUE TITLE
GKE staging tests broken 

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#3861] opened 2017-08-02 07:10 UTC
https://k8s-testgrid.appspot.com/google-gke-staging#gci-gke-staging&show-stale-tests=
https://k8s-testgrid.appspot.com/google-gke-staging#gci-gke-staging-parallel&show-stale-tests=

These are broken since after test-infra commit d827b479c
I suspect https://github.com/kubernetes/test-infra/pull/3818

cc/ @zmerlynn @krzyzacy @kubernetes/test-infra-maintainers

**Comment by zmerlynn** [comment] 2017-08-02 16:34
/assign
This looks like a dupe of #49939, but #49960 landed already. Hm.

**Comment by zmerlynn** [comment] 2017-08-02 16:35
Oh, yeah, https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-staging/2942/ is still running. You can see `gci-gke-staging-parallel` is already cleared.

**Closed by zmerlynn** 2017-08-02 16:35 UTC
