### ISSUE TITLE
Should "leader election lost" not be a fatal error?

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/test-infra#21005] opened 2021-02-24 19:40 UTC
Since leader election losses are expected, it's confusing to have them logged as a fatal error (and alerting should catch cases where components repeatedly fail to come up). Should these be a less severe warning instead?

Error:
```
jsonPayload: {
  component: "prow-controller-manager"   
  error: "leader election lost"   
  file: "prow/cmd/prow-controller-manager/main.go:187"   
  func: "main.main"   
  level: "fatal"   
  msg: "failed to start manager"   
 }
```

/area prow
/cc @alvaroaleman

**Comment by alvaroaleman** [comment] 2021-02-24 19:59
The binary needs to exit for safety reasons, so it must be a fatal error. If this happens repeatedly, that is indicative of your apiserver or the controller being resource starved.

**Comment by chaodaiG** [comment] 2021-03-16 18:04
Checked k8s prow logs, and it appears that these errors are legit errors caused by:
```
jsonPayload: {
message: "error retrieving resource lock default/prow-sinker-leaderlock: Get "https://10.111.240.1:443/api/v1/namespaces/default/configmaps/prow-sinker-leaderlock": dial tcp 10.111.240.1:443: connect: connection refused"
source: "leaderelection.go:325"
pid: "1"
}
```

I think the pod temporarily lost connection to api server and caused this

**Comment by chaodaiG** [comment] 2021-03-16 18:05
I would suggest close this bug, WDYT @michelle192837 ?

**Comment by chaodaiG** [comment] 2021-03-17 16:31
Synced offline with @michelle192837 
/close

**Closed** 2021-03-17 16:31 UTC
Labels: area/prow, kind/cleanup, kind/oncall-hotlist
