### ISSUE TITLE
Prowjob result and finished.json result differ

### ISSUE THREAD

**Issue by Ark-kun** [kubernetes/test-infra#19054] opened 2020-08-29 08:49 UTC
**What happened**:

Prow says that PR tests have failed. Tide says they've succeeded.

https://prow.k8s.io/pr-history/?org=kubeflow&repo=pipelines&pr=4427 (The tests have only ran once - there is a single column)
![image](https://user-images.githubusercontent.com/1829149/91632931-45e31700-e999-11ea-848f-705af14584da.png)

https://prow.k8s.io/pr?query=is%3Apr+repo%3Akubeflow%2Fpipelines+author%3ABobgy+head%3Arm_travis
![image](https://user-images.githubusercontent.com/1829149/91632948-5dba9b00-e999-11ea-846d-d8efd228ef3b.png)

The tests fail the same weird way as in https://github.com/kubernetes/test-infra/issues/19028 - `Test started last Thursday at 9:05 PM failed after 4s` and the build log is empty.

/cc @alvaroaleman

**Comment by alvaroaleman** [comment] 2020-08-29 16:49
/retitle Prowjob result and finished.json result differ
/area prow

Thanks for the report, the difference you see here happens because the ProwJob object is considered a success (and thats whats used by Tide and Crier, who does the github reporting), but the `finished.json` file states the job was a failure: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/4427/kubeflow-pipeline-e2e-test/1299196365082988547/finished.json

Looking at the pod, all containers finished with RC0 so the assessment on the ProwJob seems correct to me. I am very surprised as to why the `finished.json` states something different.

@Ark-kun do you happen to still have the `ae7257b1-e8e3-11ea-9361-1abbdc03e1a6` pod in your system and if yes, could you post the log of the `sidecar` container?

**Comment by Ark-kun** [comment] 2020-09-02 07:14
/cc @jlewi Do you happen to have access to the prow cluster/project?
TBH, I'm not fully aware where the jobs are executed.

**Comment by jlewi** [comment] 2020-09-14 13:19
I think we can close this issue. asI believe this is working as intended as far as prow is concerned.

@Ark-kun you should look at your tests to figure out what is writing finished.json and why the container is exiting with non-zero exit code in the event some tests succeeded.

**Comment by alvaroaleman** [comment] 2020-09-14 13:22
@jlewi `finished.json` is uploaded by the decoration utils, so it does look like a bug in Prow to me

**Comment by jlewi** [comment] 2020-09-14 14:41
@alvaroaleman You might be right. I think kubeflow/pipelines might be using the decoration utils. In a lot of the other Kubeflow tests we aren't using the decoration utils but writing the finished.json ourselves.

**Comment by alvaroaleman** [comment] 2020-09-14 14:57
@jlewi oh okay. Is there a chance that the `finished.json` was uploaded by your tooling and not the `sidecar`?

**Comment by jlewi** [comment] 2020-09-15 15:21
@Ark-kun should be able to answer that question.

**Comment by PatrickXYS** [comment] 2020-09-23 18:46
I think [sidecar](https://github.com/kubernetes/test-infra/tree/4ff12a92583cb3aae6c819f3af17935730ad3bb9/prow/sidecar) should provide two paths:

1. By-default it reports the output (including `finished.json`) to disk.
2. Provide option to disable sidecar when users have their customized uploading output logic, such as we did in [kubeflow/testing ](https://github.com/kubeflow/testing/blob/b5e19628054999cb7e7831ae181d81a48078fdf2/py/kubeflow/testing/prow_artifacts.py#L109-L114) repo

Not sure if we enable two paths and document somewhere. @alvaroaleman

**Comment by Ark-kun** [comment] 2020-10-12 22:29
> @jlewi oh okay. Is there a chance that the `finished.json` was uploaded by your tooling and not the `sidecar`?

To the extent of my knowledge, our test code does not generate `finished.json` files.

**Comment by Ark-kun** [comment] 2020-10-12 22:33
> @jlewi finished.json is uploaded by the decoration utils, so it does look like a bug in Prow to me
> > @jlewi oh okay. Is there a chance that the `finished.json` was uploaded by your tooling and not the `sidecar`?
 
> To the extent of my knowledge, our test code does not generate `finished.json` files and we use `decorate: true`. https://github.com/kubernetes/test-infra/blob/668c803e4e68d0d3016d6fbb3fee616e7ab0d17b/config/jobs/kubeflow/kubeflow-presubmits.yaml#L349

**Comment by PatrickXYS** [comment] 2020-10-12 23:13
To clarify, our code generate `finished.json`, 

https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/prow_artifacts.py#L264

And since we enabled `decorate: true`, sidecar re-write the `finished.json` file

**Closed** 2021-03-12 01:30 UTC
Labels: area/prow, kind/bug, lifecycle/rotten
