### ISSUE TITLE
go get tackle failing with OpenAPIv2: cannot find module

### ISSUE THREAD

**Issue by nieebel** [kubernetes/test-infra#25870] opened 2022-04-05 13:57 UTC
**What happened**:
Trying to follow https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md 
```
docker run -it -v golang:1.17.8-bullseye bash -c "go get -u k8s.io/test-infra/prow/cmd/tackle"
```
(same for golang 1.11, 1.12, 1.13, 1.14, 1.15, 1.16 image)

But this leads to 

```
k8s.io/test-infra/prow/cmd/tackle imports
        k8s.io/client-go/kubernetes imports
        k8s.io/client-go/discovery imports
        github.com/googleapis/gnostic/OpenAPIv2: cannot find module providing package github.com/googleapis/gnostic/OpenAPIv2
k8s.io/test-infra/prow/cmd/tackle imports
        k8s.io/client-go/kubernetes imports
        k8s.io/client-go/kubernetes/typed/auditregistration/v1alpha1 imports
        k8s.io/api/auditregistration/v1alpha1: cannot find module providing package k8s.io/api/auditregistration/v1alpha1
k8s.io/test-infra/prow/cmd/tackle imports
        k8s.io/client-go/kubernetes imports
        k8s.io/client-go/kubernetes/typed/batch/v2alpha1 imports
        k8s.io/api/batch/v2alpha1: cannot find module providing package k8s.io/api/batch/v2alpha1
k8s.io/test-infra/prow/cmd/tackle imports
        k8s.io/client-go/kubernetes imports
        k8s.io/client-go/kubernetes/typed/settings/v1alpha1 imports
        k8s.io/api/settings/v1alpha1: cannot find module providing package k8s.io/api/settings/v1alpha1
k8s.io/test-infra/prow/cmd/tackle imports
        k8s.io/test-infra/prow/flagutil imports
        sigs.k8s.io/controller-runtime/pkg/client imports
        k8s.io/client-go/metadata: cannot find module providing package k8s.io/client-go/metadata
```

**What you expected to happen**:
tackle successful installed to proceed with prow deployment

**edit**: workaround found: `bazel run //prow/cmd/tackle` https://github.com/clarketm/prow/blob/master/getting_started_deploy.md

**Comment by BenTheElder** [comment] 2022-05-02 22:19
unfortunately you cannot `go get` this repo because `go get` does not respect `replace` statements. 
you will need to clone the repo and then you can use `go build` or `go install`.

https://github.com/kubernetes/test-infra/pull/26092 updated the docs, https://github.com/kubernetes/test-infra/issues/25950 was a dupe of this issue.

**Closed by BenTheElder** 2022-05-02 22:19 UTC
Labels: kind/bug, needs-sig
