### ISSUE TITLE
prow: add a test to blocker list per-PR when the test is triggered manually

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#3740] opened 2017-07-27 15:36 UTC
It would be cool if, when a PR has a non-blocking test triggered for it manually, that either this test would automatically become part of the default trigger set and become blocking for the PR or if there were a bot command to add it to the list as well.

/area prow
/cc @kargakis @bparees

**Comment by kargakis** [comment] 2017-07-27 15:43
Seems like a munger issue. The easiest way I can think of is the SQ blocks on the context if the context exists in the PR, otherwise it is not.

/area mungegithub

**Comment by spxtr** [comment] 2017-07-27 17:04
@rmmh I think was interested in this.

**Comment by stevekuznetsov** [comment] 2017-09-26 15:42
Also necessary if a test gets selected by touching changed paths

**Comment by kargakis** [comment] 2017-10-31 20:01
Dupe of https://github.com/kubernetes/test-infra/issues/1351

**Closed by kargakis** 2017-10-31 20:01 UTC
Labels: area/mungegithub, area/prow
