### ISSUE TITLE
Mungegithub using up github tokens quickly

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#2969] opened 2017-06-05 23:26 UTC
Looks like it sleeps for around 20 minutes in each hour.

```
I0605 23:20:14.700547       1 mungegithub.go:79] Not sleeping as we took more than 20s to complete one loop
I0605 23:20:14.700589       1 mungegithub.go:60] Running mungers
I0605 23:20:16.222011       1 repo-updates.go:191] Loaded config from /gitrepos/kubernetes:7bbc615b97872c1b6fdd6d4deb03d246c4439af8
E0605 23:20:29.865668       1 github.go:96] *****************
E0605 23:20:29.865845       1 github.go:97] Ran out of github API tokens. Sleeping for 22.41890561125 minutes
E0605 23:20:29.866178       1 github.go:98] *****************
E0605 23:20:32.635188       1 github.go:96] *****************
E0605 23:20:32.635356       1 github.go:97] Ran out of github API tokens. Sleeping for 22.372746946016665 minutes
E0605 23:20:32.635635       1 github.go:98] *****************
E0605 23:20:45.707105       1 github.go:96] *****************
E0605 23:20:45.707299       1 github.go:97] Ran out of github API tokens. Sleeping for 22.15488174411667 minutes
E0605 23:20:45.707651       1 github.go:98] *****************
```

/cc @rmmh @fejta @grodrigues3 @apelisse

**Comment by foxish** [comment] 2017-06-05 23:32
cc @kubernetes/sig-contributor-experience-bugs

**Comment by apelisse** [comment] 2017-06-28 17:36
Maybe found the cause, sent an email to @brendanburns as an answer to the bulk-lgtm announcement (but didn't want to include kubernetes-dev):

> Hi Brendan,
>
> I strongly suspect bulk-lgtm to be running high on the github token.
> 
> The token usage has gone crazy since you sent that announcement email: > http://velodrome.kubernetes.io/dashboard/db/monitoring?panelId=1&fullscreen&from=1491375600000&to=1492239600000
>
> Correlation is not causation, let's go deeper :-)
>
> https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/bulk-lgtm.go#L110
> I can see PRs being added to this list, but never removed
> https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/bulk-lgtm.go#L280
> That seems like a lot of `GetPR()` (this github call can't really be cached efficiently).
> 
> Probably orthogonal issue: the app has been running for 6 days, and it's using a ton of memory:
> bulk-lgtm-2847801649-rc4lz                 1m           1631Mi
> 
> As an experiment, would you mind switching to a different token in bulk-lgtm and see if that's the culprit?

**Comment by apelisse** [comment] 2017-06-28 17:38
Something else that I find suspicious

```
> kubectl logs bulk-lgtm-2847801649-rc4lz
E0621 21:42:51.215449       1 github.go:97] *****************
E0621 21:42:51.306282       1 github.go:98] Ran out of github API tokens. Sleeping for 31.77974261396667 minutes
E0621 21:42:51.306462       1 github.go:99] *****************
E0621 22:38:36.911216       1 github.go:97] *****************
E0621 22:38:36.912435       1 github.go:98] Ran out of github API tokens. Sleeping for 36.018146487766664 minutes
E0621 22:38:36.912499       1 github.go:99] *****************
E0621 23:40:06.506259       1 github.go:97] *****************
E0621 23:40:06.507783       1 github.go:98] Ran out of github API tokens. Sleeping for 35.524896030166666 minutes
E0621 23:40:06.507869       1 github.go:99] *****************
E0622 00:58:56.431809       1 github.go:97] *****************
E0622 00:58:56.431995       1 github.go:98] Ran out of github API tokens. Sleeping for 16.692803342583332 minutes
E0622 00:58:56.432067       1 github.go:99] *****************
E0622 01:58:17.407295       1 github.go:97] *****************
E0622 01:58:17.407312       1 github.go:98] Ran out of github API tokens. Sleeping for 18.343212174283334 minutes
E0622 01:58:17.407321       1 github.go:99] *****************
E0622 03:01:32.409488       1 github.go:97] *****************
E0622 03:01:32.411795       1 github.go:98] Ran out of github API tokens. Sleeping for 16.09317539168333 minutes
E0622 03:01:32.411947       1 github.go:99] *****************
E0622 07:11:51.206209       1 github.go:97] *****************
E0622 07:11:51.206374       1 github.go:98] Ran out of github API tokens. Sleeping for 6.846563317 minutes
E0622 07:11:51.206415       1 github.go:99] *****************
E0622 08:14:16.907260       1 github.go:97] *****************
E0622 08:14:16.907489       1 github.go:98] Ran out of github API tokens. Sleeping for 5.4182125222 minutes
E0622 08:14:16.907575       1 github.go:99] *****************
E0622 09:12:54.088242       1 github.go:97] *****************
E0622 09:12:54.088588       1 github.go:98] Ran out of github API tokens. Sleeping for 7.798529668416666 minutes
E0622 09:12:54.088769       1 github.go:99] *****************
E0622 10:06:16.107308       1 github.go:97] *****************
E0622 10:06:16.107503       1 github.go:98] Ran out of github API tokens. Sleeping for 15.431545024666667 minutes
E0622 10:06:16.107546       1 github.go:99] *****************
E0622 15:08:04.206986       1 github.go:97] *****************
E0622 15:08:04.207785       1 github.go:98] Ran out of github API tokens. Sleeping for 15.146550382216667 minutes
E0622 15:08:04.207865       1 github.go:99] *****************
E0622 16:14:06.208003       1 github.go:97] *****************
E0622 16:14:06.208035       1 github.go:98] Ran out of github API tokens. Sleeping for 9.9298667555 minutes
E0622 16:14:06.208048       1 github.go:99] *****************
```

**Comment by grodrigues3** [comment] 2017-06-28 17:47
@apelisse does the bulk lgtm tool have its own token?  Were you ever able to confirm your theory regarding GetPRs?

**Comment by apelisse** [comment] 2017-06-28 17:50
> does the bulk lgtm tool have its own token?

I verified and the cluster uses the same token (I may be wrong).

> Were you ever able to confirm your theory regarding GetPRs?

Not yet. As suggested above, the fastest way to verify would be to turn off bulk-lgtm or let it use a different token.

**Comment by apelisse** [comment] 2017-06-28 20:24
Bulk-lgtm is now running with my very own token.

**Comment by spiffxp** [comment] 2017-06-29 21:24
@apelisse thanks for the quick workaround

**Comment by spxtr** [comment] 2017-07-12 16:38
Possible to close this? It looks like the munger is back to using a normal amount of tokens.

**Comment by apelisse** [comment] 2017-07-12 17:12
yes that was fixed.

**Closed** 2017-07-12 17:16 UTC
Labels: area/mungegithub

**Comment by fejta** [comment] 2017-07-12 17:54
Is it using it's own account or just it's own token?

**Comment by apelisse** [comment] 2017-07-12 20:12
It uses the same secret key in the cluster, hence the exact same token as the submit-queue.
