### ISSUE TITLE
green batch does not merge with tide

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#13149] opened 2019-06-25 08:13 UTC
**What happened**: https://prow.k8s.io/?repo=kubernetes%2Fkubernetes&type=batch has the following batch: `#75223, #78922, #79309, #79316, #79317` with all green tests. 
For some reason it doesn't appear any of these merged. https://prow.k8s.io/tide-history?repo=kubernetes%2Fkubernetes 

![image](https://user-images.githubusercontent.com/917931/60081065-f5fa2780-96e5-11e9-81be-a730e074a7dc.png)

![image](https://user-images.githubusercontent.com/917931/60081032-e2e75780-96e5-11e9-9000-d2ee9db2c303.png)

![image](https://user-images.githubusercontent.com/917931/60081221-33f74b80-96e6-11e9-9c1a-d73baacf8f3d.png)

I don't understand why the tide history is all `TRIGGER` / `TRIGGER_BATCH` and only showing one pool.

**What you expected to happen**: Green batches should merge.

**How to reproduce it (as minimally and precisely as possible)**: use tide. y u no merge.

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
/area prow/tide
/assign @cjwagner

**Comment by BenTheElder** [comment] 2019-06-25 08:14
It would be helpful if the tide history page recorded why it transitioned away. Nearly all entries are a green "succeeded" check but most of them seem to be succeeding at triggering only...

I can't find any details on any of the pages to explain why this batch wasn't merged.

**Comment by cjwagner** [comment] 2019-06-25 21:00
Good catch Ben, this is definitely a weird scenario that isn't easy to understand from the `deck` pages. The batch succeeded, but the PRs didn't merge immediately after it finished and another batch was triggered while the first was still running.  Here is what happened:
1) The batch was triggered normally.
2) Next sync loop Tide triggeds a serial retest of 75223.
3) The serial retest of 75223 failed which removed 75223 from the pool and meant that the currently running batch was not longer considered valid. (We can't just respect the batch results because the PR labels may have changed or the status context may be red.)
4) Tide triggeds a new batch.
5) The retester bot retested 75223 which causes the red context to switch to pending allowing 75223 back into the merge pool. (Pending blocking contexts don't kick a PR out of the merge pool so that PR's don't leave and reenter the pool while retesting.)
6) The original batch then became valid again because all it's PRs were in the pool. The PRs are merged.

> It would be helpful if the tide history page recorded why it transitioned away. Nearly all entries are a green "succeeded" check but most of them seem to be succeeding at triggering only...

Yeah, the Tide history page only shows Tide errors like those related to triggering or merging. It doesn't show job failures. Aggregating job results after the jobs have completed and amending the results to `TRIGGER` and `TRIGGER_BATCH` entries would add a decent amount of complexity to Tide. Currently Tide only considers ProwJobs for pooled PRs, but this would require reconciling all completed presubmits with the action history. We'd essentially need a Tide crier reporter to retroactively update action history entries with aggregated job results when all the jobs complete.

I think adding links to the front page with relevant queries and recording the currently pooled PRs in each action history entry so we can display the diff between each entry would be easier to implement and provide more details. If the problem with the green checks is just that they can be misconstrued as the job result perhaps that just needs to be clarified somehow?

**Comment by BenTheElder** [comment] 2019-06-25 21:04
Thanks for the super detailed writeup.

Do we know why 2) happened?

Does 3) actually make sense from a logical standpoint? 
If the PR passes as a batch then perhaps the batch includes fixes that make the tests pass that otherwise fail serially?

**Comment by cjwagner** [comment] 2019-06-25 21:32
> Do we know why 2) happened?

Yeah this is expected. Tide serially tests a PR whenever it is running a batch so that if the batch fails and the serial test succeeds it can still merge something. Additionally, the serial PR is chosen in the same way we choose batch members so that we almost always pick one from the batch (we should probably fix this to just pick directly from the batch) so that if the batch fails we can remove one of the member PRs for the next batch.
Tide's `takeAction` method for reference: https://github.com/kubernetes/test-infra/blob/4a79c95955a670b16d2c96d397860bf511645153/prow/tide/tide.go#L1037-L1070

> Does 3) actually make sense from a logical standpoint?
> If the PR passes as a batch then perhaps the batch includes fixes that make the tests pass that otherwise fail serially?

Yeah from a purely testing standpoint thats right, but there are more factors than just the tests. In particular a PR may have left the pool because a `do-not-merge/evil-code` label was added or the batch results may no longer be applicable if one of the PRs had new commits pushed since the tests started.

**Comment by BenTheElder** [comment] 2019-06-25 21:35
SGTM for 2, regarding 3 though...

> Yeah from a purely testing standpoint thats right, but there are more factors than just the tests. In particular a PR may have left the pool because a do-not-merge/evil-code label was added or the batch results may no longer be applicable if one of the PRs had new commits pushed since the tests started.

was that the case here though? or was it just a test failure? if it's just a test failure I don't think it should be removed.

**Comment by cjwagner** [comment] 2019-06-25 21:53
It was just a test failure, but having either a test failure or a forbidden label prevents a PR from being in the pool which is the reason the batches are invalidated. PRs that are failing tests can't be in the pool or we would wrongly consider them for serial retesting or batch membership.
Since we manually filter out PRs with failing tests from the PRs returned by the Tide queries when constructing the pool, we could instead separate PRs with failing tests into a new category and special case their handling in `accumulateBatch` to get the behavior you are describing. It would technically be a breaking change because Tide would then require that branch protection is configured to allow it to ignore the status context requirements, but that could be handled with warnings, changes to branch-protector, and a migration period.

**Comment by BenTheElder** [comment] 2019-06-25 22:08
I see.

> It was just a test failure, but having either a test failure or a forbidden label prevents a PR from being in the pool which is the reason the batches are invalidated. PRs that are failing tests can't be in the pool or we would wrongly consider them for serial retesting or batch membership.

If the PR passed tests in a batch why wouldn't it be valid for being in another batch? Or serially retested? If it fails serially but passes in batch we have one of two things:
- a flake
- interdependent PRs (intentionally or otherwise, including EG one of them being a fix for the tests, which happens semi-frequently)

> Since we manually filter out PRs with failing tests from the PRs returned by the Tide queries when constructing the pool, we could instead separate PRs with failing tests into a new category and special case their handling in accumulateBatch to get the behavior you are describing.

I don't quite understand this part, _it was already in a running batch_, was it not? Why would test results from outside the batch affect it's "in batch" status?

> It would technically be a breaking change because Tide would then require that branch protection is configured to allow it to ignore the status context requirements, but that could be handled with warnings, changes to branch-protector, and a migration period.

Or by setting statuses from batches maybe?

**Comment by stevekuznetsov** [comment] 2019-06-25 22:09
It's been brought up to add metrics to `tide` that show per-PR time spent in the pool (waiting and active), number of transitions, etc -- this would require committing pool state at each sync to a store and using  that data to calculate the above metrics. If we do that, then we can also use that information to show pool states and transitions, which would help very much to understand what's happening under the hood.

**Comment by cjwagner** [comment] 2019-06-26 18:44
> If the PR passed tests in a batch why wouldn't it be valid for being in another batch? Or serially retested?

Good point. If it has passed tests in the batch we know it is one of the cases you described so we could optimize that case if the PRs all still meet the other merge requirements.

> Why would test results from outside the batch affect its "in batch" status?

Currently Tide ignores batches that are not composed of entirely pooled PRs so that if a PR leaves the pool for any reason (failing context, `do-not-merge` label, cancelled required review, etc.) we don't accidentally merge it.

I think the root of the problem is that we are grouping all our merge requirements into a concept of being in the merge pool, but we now want to special case one of these requirements (the status context requirements) so that we can ignore the requirement in specific cases where we know the failed contexts are flakes or missing dependent PRs. We can't just consider having either successful batch OR successful serial results as meaning "passed tests" in all cases though. For example a PR that has a failing context and is in a successful batch could be eligible for immediate merge, but if one of the other PRs in the batch gets a `do-not-merge` label and leaves the pool, preventing batch merge, the first PR cannot even be safely retested because if the PRs in the batch were dependent that would cause a retest loop on a job that repeatedly fails. All this is possible, but I suspect there will be other complexities like that.

> Or by setting statuses from batches maybe?

I mean that Tide would need the ability to force merge PRs with red status contexts that it knows are a result of flakes or missing dependent PRs based on successful batch results.  So setting the `tide` status for batches (or a new status context) wouldn't make a difference.
I also don't think Tide should be overwriting arbitrary status contexts that are blocking merge if that is what you are suggesting since it doesn't "own" those statuses and they could be overwritten again immediately if another service is reacting to webhooks.

**Comment by BenTheElder** [comment] 2019-06-28 20:38
All good points... on comment :-)


> I also don't think Tide should be overwriting arbitrary status contexts that are blocking merge if that is what you are suggesting since it doesn't "own" those statuses and they could be overwritten again immediately if another service is reacting to webhooks.

I would expect the github reporter in crier could (possibly optionally) report this, plank / now crier still own reporting. But tide could integrate with expecting this.

**Closed** 2019-11-28 20:17 UTC
Labels: area/prow/tide, kind/bug, lifecycle/rotten
