### ISSUE TITLE
Tide error: broken pipe

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#19981] opened 2020-11-18 19:55 UTC
```
jsonPayload: {
file: "prow/tide/history/history.go:183"
error: "write tcp 10.108.11.15:8888->10.108.6.28:47268: write: broken pipe"
level: "error"
func: "k8s.io/test-infra/prow/tide/history.(*History).ServeHTTP"
component: "tide"
msg: "Writing JSON history response."
}
```

**Comment by chases2** [comment] 2020-11-18 20:13
Occurred twice in a row (1 minute apart), but then seemed to stop.

**Comment by e-blackwelder** [comment] 2020-11-18 20:15
It looks like the browser's side of the HTTP/TCP connection is closing "unexpectedly": users could be canceling the page load, navigate away, refresh the page, etc.

Per:
https://github.com/kubernetes/test-infra/blob/master/prow/tide/history/history.go#L182

... This is not a bug. However, we should lower the "severity" of the logs so we don't panic about this again. :)

**Closed** 2020-12-02 03:14 UTC
Labels: kind/bug, kind/oncall-hotlist
