### ISSUE TITLE
GHProxy: Path not handled

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/test-infra#14175] opened 2019-09-03 17:00 UTC
Got error: "Path not handled. This is a bug in GHProxy, please open an issue against the kubernetes/test-infra repository with this error message." So doing that :P (This isn't all of them, but it should be pretty representative of the bunch).

jsonPayload: {
  component:  "ghproxy"   
  file:  "ghproxy/ghmetrics/ghpath.go:141"   
  func:  "k8s.io/test-infra/ghproxy/ghmetrics.GetSimplifiedPath"   
  level:  "warning"   
  msg:  "Path not handled. This is a bug in GHProxy, please open an issue against the kubernetes/test-infra repository with this error message."   
  path:  "/repos/kubernetes-sigs/controller-runtime/branches/feature/modules/protection"   
 }

jsonPayload: {
  component:  "ghproxy"   
  file:  "ghproxy/ghmetrics/ghpath.go:141"   
  func:  "k8s.io/test-infra/ghproxy/ghmetrics.GetSimplifiedPath"   
  level:  "warning"   
  msg:  "Path not handled. This is a bug in GHProxy, please open an issue against the kubernetes/test-infra repository with this error message."   
  path:  "/repos/kubernetes/dashboard/branches/plugin/base/protection"   
 }

jsonPayload: {
  component:  "ghproxy"   
  file:  "ghproxy/ghmetrics/ghpath.go:141"   
  func:  "k8s.io/test-infra/ghproxy/ghmetrics.GetSimplifiedPath"   
  level:  "warning"   
  msg:  "Path not handled. This is a bug in GHProxy, please open an issue against the kubernetes/test-infra repository with this error message."   
  path:  "/repos/kubernetes-incubator/external-dns/branches/bugfix/style-faq/protection"   
 }

jsonPayload: {
  component:  "ghproxy"   
  file:  "ghproxy/ghmetrics/ghpath.go:141"   
  func:  "k8s.io/test-infra/ghproxy/ghmetrics.GetSimplifiedPath"   
  level:  "warning"   
  msg:  "Path not handled. This is a bug in GHProxy, please open an issue against the kubernetes/test-infra repository with this error message."   
  path:  "/repos/kubernetes-incubator/external-dns/branches/pr/531/protection"   
 }

/area ghproxy
/assign @stevekuznetsov

**Comment by stevekuznetsov** [comment] 2019-09-03 17:33
Dupe of https://github.com/kubernetes/test-infra/issues/13789

Thanks, Michelle!

**Closed by stevekuznetsov** 2019-09-03 17:33 UTC
Labels: area/ghproxy, kind/bug
