### ISSUE TITLE
how can i get  trigger command args

### ISSUE THREAD

**Issue by tinyc-z** [kubernetes/test-infra#24556] opened 2021-12-06 17:44 UTC
i have a trigger job, i want to get a param for my jobshell, 
for example yaml:
...
rerun_command: "/tag <tag_name>"
trigger: "(?mi)^/tag <tag_name>"
...
`tag_name` is a variable
so how can i use the `tag_name` in my jobshell, like ${JOB_NAME} or ${REPO_OWNER}

**Comment by petr-muller** [comment] 2021-12-07 10:29
This looks like a duplicate of #19456

**Comment by BenTheElder** [comment] 2022-01-14 22:25
/remove-sig k8s-infra
/sig testing
/remove-kind bug
/kind feature
/area prow

This is not a feature that exists.

https://github.com/kubernetes/test-infra/issues/19456 and https://github.com/kubernetes/test-infra/issues/23846

**Closed** 2022-06-14 00:08 UTC
Labels: area/prow, sig/testing, kind/feature, lifecycle/rotten
