### ISSUE TITLE
Malformed prowjobs.prow.k8s.io can break Prow cluster

### ISSUE THREAD

**Issue by jprzychodzen** [kubernetes/test-infra#23283] opened 2021-08-17 22:31 UTC
**What happened**:
I've applied on the cluster manually edited job. Plank was unable to unmarshal the object, and entered into the restart loop. It seems that CRD definition [1] is much more accepting than Go object[2].

[1] https://github.com/kubernetes/test-infra/blob/master/config/prow/cluster/starter-gcs.yaml#L153
[2] https://github.com/kubernetes/test-infra/blob/master/prow/apis/prowjobs/v1/types.go#L115

**What you expected to happen**:
Malformed prowjobs.prow.k8s.io should be validated on kube-apiserver level by appropriate CRD. If not possible, then malformed objects should be logged then ignored, instead of crashlooping Prow components.

**How to reproduce it (as minimally and precisely as possible)**:

Change field to non-matching type, for example set `spec.agent` to object `{}`. This results in error like 

```
"external/io_k8s_client_go/tools/cache/reflector.go:167: Failed to watch *v1.ProwJob: failed to list *v1.ProwJob: v1.ProwJobList.Items: []v1.ProwJob: v1.ProwJob.Spec: v1.ProwJobSpec.Agent: ReadString: expects " or n, but found {, error found in #10 byte of ...|{"agent":{},"cluster|..., bigger context ...
```

**Comment by alvaroaleman** [comment] 2021-08-17 22:50
Duplicate of https://github.com/kubernetes/test-infra/issues/14925
/close

**Closed** 2021-08-17 22:50 UTC
Labels: kind/bug, sig/testing
