### ISSUE TITLE
Store artifacts in Persistent Volume (Claim) via plank

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/test-infra#15568] opened 2019-12-11 14:36 UTC
**What would you like to be added**:

It would be good to use the build artifact collector without a GCS bucket to have a better experience on bare-metal clusters. I could imagine that a simple PVC could be used as artifact storage as well, WDYT?

**Why is this needed**:

I don't have a GCS bucket right now and I'm not sure if there is a way around this.

**Comment by stevekuznetsov** [comment] 2019-12-11 17:55
This is related to https://github.com/kubernetes/test-infra/issues/11260

I think supporting a PV as a specific backend of many would be a good approach! That might be more challenging on the read side of things when `deck` needs to get the data back out, as you'd need to run a file server to let the other downstream components read it.

**Comment by saschagrunert** [comment] 2019-12-11 18:21
Okay, what about shipping a `ReadWriteMany` PVC, which can be used by deck and plank?

After that, we could also ship another artifact serving component, like a simple web server thingy giving access to the artifacts.

**Comment by stevekuznetsov** [comment] 2019-12-12 00:01
I'm not sure I would personally go for a shared PVC since that would require (I think) all of the `plank` and `deck` replicas to exist on one node, which somewhat nullifies gains from horizontal scaling across zones/fleets. I think a good start would be to write a PVC-backed implementation of the remote write/read functionality as described by @fejta in the other thread.

**Comment by alvaroaleman** [comment] 2019-12-12 11:10
Changing all of Prow do support a volume as an object storage implementation is IMHO not a great idea and will only work with rwx volumes anyways which is to my knowledge mostly implemented via nfs and that tends to add challenges on its own.

IMHO this use-case should be satisfied by adding s3 support and then using minio with a pvc as backing store, which would make this a duplicate of #11260. @saschagrunert Wdyt?

**Comment by alvaroaleman** [comment] 2019-12-12 11:16
Also, we need to access object storage from the jobs themselves to upload the artifacts, so the only way to make this work would be to implement our own object storage and that doesn't make sense, since there are existing object storage implementations.

**Comment by stevekuznetsov** [comment] 2019-12-12 18:13
Yeah, that's what I meant by 

> PVC-backed implementation of the remote write/read functionality

If we can use off-the-shelf libraries and front them with the s3 API then I agree this is a dupe.

**Closed** 2020-05-10 20:20 UTC
Labels: kind/feature, lifecycle/rotten

**Comment by alvaroaleman** [comment] 2020-05-10 20:21
https://github.com/kubernetes/test-infra/pull/17183 plus https://min.io/download#/kubernetes will fix this usecase

**Comment by saschagrunert** [comment] 2020-05-10 20:29
Ah yeah that’s a good idea to use minio. Thanks for the link!
